// Generated by scripts/sync-spec.ts from spec/openapi/cell.json. Do not edit.
/**
 * Ownership and effects: the coordination decision, declarations, claims and locks, effects exactly once,
 * handoffs, suppressions and the contact token's public keys.
 */

import type { Handle, ObjectRef } from "./common.js";
import type { Verification } from "./vocabulary.js";

/** The claim a case closes, with the epoch it got when it was accepted. */
export interface ReleaseDetail {
  claim_id: string;
  epoch: number;
}

export interface CaseClosed {
  agent: string;
  detail: ReleaseDetail;
  kind: "case.closed";
  object?: ObjectRef | null;
  subject?: Handle | null;
}

/**
 * An owner lease or a case, held by the declaring agent. `level` defaults to the space's least
 * restrictive level.
 */
export interface LeaseDetail {
  intents?: string[];
  lease_s: number;
  level?: string | null;
}

export interface CaseOpened {
  agent: string;
  detail: LeaseDetail;
  kind: "case.opened";
  object?: ObjectRef | null;
  subject?: Handle | null;
}

export interface ChannelState {
  free_form_until?: string | null;
  quiet_until?: string | null;
  template_required?: boolean;
}

export type EffectKind = "delivery" | "document" | "notice" | "filing" | "paid_call" | "external_action";

/**
 * What an agent is about to do. Without a subject there is no budget, suppression or owner to consult:
 * such a check only asks about the effect key.
 */
export interface CheckRequest {
  agent: string;
  channel?: string | null;
  /**
   * The token's `rcpt`, computed by a caller that holds the gateway's key, when the destination is not the
   * subject's handle.
   */
  destination_hash?: string | null;
  direction: "inbound" | "outbound";
  /** The business fact's key; reserved atomically when nothing holds it. */
  effect_key?: string | null;
  effect_kind?: EffectKind;
  gateway_id?: string | null;
  intent: string;
  object?: ObjectRef | null;
  purpose: string;
  subject?: Handle | null;
  task?: string | null;
}

export interface CheckBatchRequest {
  checks: CheckRequest[];
}

export interface CommitmentRef {
  id: string;
  type: string;
  valid_until?: string | null;
}

export interface ContactBudget {
  next_allowed_at?: string | null;
  remaining: number;
}

/** `none` means nothing held the key and this check reserved it: the caller acts and then declares. */
export interface EffectStatus {
  attempt?: number | null;
  state: "none" | "in_flight" | "done" | "unknown_outcome";
}

export interface Lock {
  holder: string;
  kind: string;
  task?: string | null;
  until: string;
}

export type ClaimKind = "owner" | "case" | "task_lock";

/**
 * The three ways in: a declaration through the API, an observation mapped from a webhook, an observation
 * the company's worker read and sent.
 */
export type ClaimVia = "declaration" | "mapping" | "worker";

/**
 * Who holds the subject or the object now: the most restrictive valid claim, where it came from and
 * until when. `epoch` fences a release.
 */
export interface Owner {
  epoch: number;
  holder: string;
  kind: ClaimKind;
  level: string;
  since: string;
  source: string;
  valid_until: string;
  via: ClaimVia;
}

export interface PromiseRef {
  due?: string | null;
  id: string;
  owner: string;
}

/**
 * The coordination decision. `reasons` are codes (the coordination spec, 4); `holder` is who to hand
 * off to with `handoff_to`. `contact_token` comes only with an allowed outbound contact of a purpose that
 * needs one.
 */
export interface CheckResult {
  channel?: ChannelState | null;
  commitments_active?: CommitmentRef[];
  contact_budget?: Record<string, ContactBudget>;
  contact_token?: string | null;
  decision: "allow" | "defer" | "deny" | "handoff_to";
  decision_id: string;
  effect?: EffectStatus | null;
  holder?: string | null;
  locks?: Lock[];
  owner?: Owner | null;
  promises_open?: PromiseRef[];
  reasons?: string[];
  suppressions?: string[];
  valid_for_s: number;
}

export interface CheckBatchResponse {
  results: CheckResult[];
}

export interface ClaimRelease {
  epoch: number;
}

/**
 * A declared claim, held by `holder`. `level` defaults to the space's least restrictive level; a
 * declaration is refused (409 `lease_held`) while another holder's claim is at least as restrictive, and the
 * same holder renews its own. `lease_s` is capped by the space's longest declared lease. A task lock names
 * an object and its `task`, and is refused (409 `task_locked`) while another holder has that task.
 */
export interface ClaimRequest {
  holder: string;
  intents?: string[];
  kind: ClaimKind;
  lease_s: number;
  level?: string | null;
  object?: ObjectRef | null;
  /** When the source saw it; an observation older than the source's last is ignored. */
  observed_at?: string | null;
  /**
   * An observation of this ownership source, read and sent by the company's worker: never refused, replacing
   * what the source said before, and capped by the source's validity.
   */
  source?: string | null;
  subject?: Handle | null;
  task?: string | null;
}

/** The person accepted or declined a commitment, maybe in a later conversation. */
export interface CommitmentDecidedDetail {
  commitment_id: string;
  outcome: "accepted" | "declined";
}

export interface CommitmentDecided {
  agent: string;
  detail: CommitmentDecidedDetail;
  kind: "commitment.decided";
  object?: ObjectRef | null;
  subject?: Handle | null;
}

/** `score` ranks commitments of a `best_wins` type: the higher holds. */
export interface CommitmentMadeDetail {
  commitment_id: string;
  score?: number | null;
  terms?: Record<string, unknown>;
  type: string;
  valid_until?: string | null;
}

export interface CommitmentMade {
  agent: string;
  detail: CommitmentMadeDetail;
  kind: "commitment.made";
  object?: ObjectRef | null;
  subject?: Handle | null;
}

export interface CommitmentWithdrawnDetail {
  commitment_id: string;
}

export interface CommitmentWithdrawn {
  agent: string;
  detail: CommitmentWithdrawnDetail;
  kind: "commitment.withdrawn";
  object?: ObjectRef | null;
  subject?: Handle | null;
}

/** An Ed25519 public key as a JWK (RFC 8037). A `retiring` key still verifies and signs nothing new. */
export interface ContactKey {
  crv?: "Ed25519";
  kid: string;
  kty?: "OKP";
  not_after?: string | null;
  space: string;
  status?: "active" | "retiring";
  x: string;
}

/** A space's public keys a gateway checks a contact token with, offline. */
export interface ContactKeys {
  keys: ContactKey[];
}

/**
 * `jti` is the contact token's; `unchecked` says the contact left without a decision, because the
 * purpose fails open and none came in time.
 */
export interface ContactMadeDetail {
  channel: string;
  decision_id?: string | null;
  gateway_id?: string | null;
  jti?: string | null;
  purpose: string;
  unchecked?: boolean;
}

export interface ContactMade {
  agent: string;
  detail: ContactMadeDetail;
  kind: "contact.made";
  object?: ObjectRef | null;
  subject?: Handle | null;
}

/**
 * A shadow run: the space's policy applied to its outbound messages already ingested, with nothing
 * enforced. `summary` holds the conflicts found and per 1,000 customers a month, without anyone in them.
 */
export interface CoordinationReport {
  days: number;
  finished_at?: string | null;
  report_id: string;
  requested_at: string;
  status: "pending" | "done" | "failed";
  summary?: Record<string, unknown>;
}

export interface CoordinationReportPage {
  items: CoordinationReport[];
  next_cursor?: string | null;
}

/** How the attempt the caller holds ended. */
export interface EffectDetail {
  attempt: number;
  effect_key: string;
  state: "done" | "failed" | "unknown_outcome";
}

export interface EffectDeclared {
  agent: string;
  detail: EffectDetail;
  kind: "effect";
  object?: ObjectRef | null;
  subject?: Handle | null;
}

export interface HandoffDetail {
  handoff_id: string;
  outcome?: string | null;
  status: "created" | "accepted" | "closed";
}

export interface HandoffDeclared {
  agent: string;
  detail: HandoffDetail;
  kind: "handoff";
  object?: ObjectRef | null;
  subject?: Handle | null;
}

export interface LeaseDeclared {
  agent: string;
  detail: LeaseDetail;
  kind: "lease";
  object?: ObjectRef | null;
  subject?: Handle | null;
}

/**
 * The subject may not be contacted for `purpose`, on `channel` or on every channel. `until` defaults to
 * the reason's own interval, or to no end.
 */
export interface SuppressionAddedDetail {
  channel?: string | null;
  purpose: string;
  reason: string;
  until?: string | null;
}

export interface SuppressionAdded {
  agent: string;
  detail: SuppressionAddedDetail;
  kind: "suppression.added";
  object?: ObjectRef | null;
  subject?: Handle | null;
}

/** Lifts what the same source suppressed for `purpose` and `channel`. */
export interface SuppressionLiftedDetail {
  channel?: string | null;
  purpose: string;
}

export interface SuppressionLifted {
  agent: string;
  detail: SuppressionLiftedDetail;
  kind: "suppression.lifted";
  object?: ObjectRef | null;
  subject?: Handle | null;
}

export interface TaskLockDetail {
  lease_s: number;
  task: string;
}

export interface TaskLockDeclared {
  agent: string;
  detail: TaskLockDetail;
  kind: "task_lock";
  object?: ObjectRef | null;
  subject?: Handle | null;
}

/**
 * What happened, after the fact: one kind of declaration, with the fields of its kind in `detail` (the
 * coordination spec, 5).
 */
export type DeclareRequest = CaseOpened | CaseClosed | LeaseDeclared | TaskLockDeclared | ContactMade | EffectDeclared | CommitmentMade | CommitmentWithdrawn | CommitmentDecided | HandoffDeclared | SuppressionAdded | SuppressionLifted;

export interface DeclareResult {
  accepted: boolean;
  decision_id?: string | null;
}

/**
 * `effect_id` is the key's keyed hash: it names the effect in paths, where the key itself, which may
 * carry a conversation id, never goes.
 */
export interface Effect {
  attempt: number;
  done_at?: string | null;
  effect_id: string;
  reserved_at: string;
  state: "reserved" | "done" | "failed" | "unknown_outcome";
}

export interface EffectReserve {
  cost_units?: number;
  effect_key: string;
  fact?: ObjectRef | null;
  kind: EffectKind;
}

export interface EffectSeen {
  effect_id: string;
  kind: EffectKind;
  state: "reserved" | "done" | "failed" | "unknown_outcome";
}

export interface EffectSettle {
  attempt: number;
  state: "done" | "failed" | "unknown_outcome";
}

/**
 * The compiled `handoff` view, at the receiving side's policy and verification level. `etag` is the
 * pack's it was compiled from, absent for a subject the memory knows nothing of yet.
 */
export interface HandoffContext {
  etag?: string | null;
  policy_version?: string | null;
  text: string;
}

export interface OpenObject {
  ref: ObjectRef;
  since?: string | null;
  state?: string | null;
}

/** How the receiving side reports back: one of `vocabulary`, by `expected_by`. */
export interface OutcomeRequest {
  expected_by?: string | null;
  vocabulary?: string[];
}

/** What a handoff carries to whoever receives it (the coordination spec, 7). */
export interface HandoffPackage {
  commitments_active?: CommitmentRef[];
  context: HandoffContext;
  created_at: string;
  effects?: EffectSeen[];
  from_agent: string;
  handoff_id: string;
  level: Verification;
  open_objects?: OpenObject[];
  outcome?: OutcomeRequest;
  owner?: Owner | null;
  promises_open?: PromiseRef[];
  reason?: string | null;
  spec?: "handoff-package.v0";
  /** Whom the handoff is about. */
  subject?: Handle | null;
  suppressions?: string[];
  target: string;
}

export interface Handoff {
  created_at: string;
  expected_by?: string | null;
  handoff_id: string;
  outcome?: string | null;
  package?: HandoffPackage | null;
  status: "created" | "accepted" | "closed" | "expired";
}

/**
 * Hands the subject to `target`. The package is compiled at `level`, the verification the receiving
 * side has of the subject, so it never carries what that side could not read.
 */
export interface HandoffCreate {
  /** The agent handing off; the calling key's name when absent. */
  agent?: string | null;
  conversation_id?: string | null;
  /** When the outcome is due; the space's default wait when absent. */
  expected_by?: string | null;
  level?: Verification;
  reason?: string | null;
  subject: Handle;
  target: string;
}

export interface HandoffOutcome {
  detail?: Record<string, unknown>;
  outcome: string;
}

export interface OwnershipClaim {
  claim_id: string;
  epoch: number;
  holder: string;
  kind: ClaimKind;
  level: string;
  valid_until: string;
}

export interface ShadowRequest {
  days?: number;
}

export interface ShadowRun {
  report_id: string;
  status: "pending" | "done";
}

/**
 * One entry of the suppression list: `key` is the subject's handle keyed with the reading source's salt
 * (the suppression-list spec); `removed` takes the entry `id` out of the reader's copy. The reason stays
 * with the producer: a vendor learns that it may not contact, never why.
 */
export interface Suppression {
  channel?: string | null;
  id: string;
  key: string;
  purpose: string;
  removed?: boolean;
  since: string;
  until?: string | null;
}

/**
 * A page of changes, oldest first. With `reset`, the reader drops its copy before applying `items`:
 * the salt changed, or the cursor is older than what the list keeps.
 */
export interface SuppressionPage {
  items: Suppression[];
  next_cursor?: string | null;
  reset?: boolean;
  salt_id: string;
}

export interface SuppressionSalt {
  salt: string;
  salt_id: string;
  valid_from: string;
}
