// Generated by scripts/sync-spec.ts from spec/openapi/cell.json. Do not edit.
/**
 * Ownership and effects: the coordination decision, declarations, claims and locks, effects exactly once,
 * handoffs, suppressions and the contact token's public keys.
 *
 * Draft: the server has not fixed these types yet, and their fields may still change.
 */

import type { Handle, ObjectRef } from "./common.js";

export interface ChannelState {
  free_form_until?: string | null;
  quiet_until?: string | null;
  template_required?: boolean;
}

export interface CheckRequest {
  agent: string;
  channel?: string | null;
  destination_hash?: string | null;
  direction: "inbound" | "outbound";
  effect_key?: string | null;
  gateway_id?: string | null;
  intent: string;
  object?: ObjectRef | null;
  purpose: string;
  subject?: Handle | null;
  task?: string | null;
}

export interface CheckBatchRequest {
  checks: CheckRequest[];
}

export interface ContactBudget {
  next_allowed_at?: string | null;
  remaining: number;
}

export interface EffectStatus {
  state: "none" | "in_flight" | "done" | "unknown_outcome";
}

export interface Lock {
  holder: string;
  kind: string;
  task?: string | null;
  until: string;
}

export interface Owner {
  epoch: number;
  holder: string;
  kind: string;
  since: string;
  source: string;
  valid_until?: string | null;
}

export interface CheckResult {
  channel?: ChannelState | null;
  commitments_active?: (Record<string, unknown>)[];
  contact_budget?: Record<string, ContactBudget>;
  contact_token?: string | null;
  decision: "allow" | "defer" | "deny" | "handoff_to";
  decision_id: string;
  effect?: EffectStatus | null;
  holder?: string | null;
  locks?: Lock[];
  owner?: Owner | null;
  promises_open?: (Record<string, unknown>)[];
  reasons?: string[];
  suppressions?: string[];
  valid_for_s: number;
}

export interface CheckBatchResponse {
  results: CheckResult[];
}

export interface ClaimRelease {
  epoch: number;
}

export interface ClaimRequest {
  holder: string;
  intents?: string[];
  kind: "owner" | "case" | "task_lock";
  lease_s: number;
  object?: ObjectRef | null;
  subject?: Handle | null;
  task?: string | null;
}

/** The spaces' Ed25519 public keys a gateway checks a contact token with, offline. */
export interface ContactKeys {
  keys: (Record<string, string>)[];
}

export interface CoordinationReportPage {
  items: (Record<string, unknown>)[];
  next_cursor?: string | null;
}

export interface DeclareRequest {
  agent: string;
  detail?: Record<string, unknown>;
  kind: "case.opened" | "case.closed" | "lease" | "task_lock" | "contact.made" | "effect" | "commitment.made" | "commitment.withdrawn" | "handoff";
  object?: ObjectRef | null;
  subject?: Handle | null;
}

export interface DeclareResult {
  accepted: boolean;
  decision_id?: string | null;
}

export interface Effect {
  attempt: number;
  done_at?: string | null;
  effect_key: string;
  reserved_at: string;
  state: "reserved" | "done" | "failed" | "unknown_outcome";
}

export interface EffectReserve {
  cost_units?: number;
  effect_key: string;
  fact?: ObjectRef | null;
  kind: "delivery" | "document" | "notice" | "filing" | "paid_call" | "external_action";
}

export interface EffectSettle {
  state: "done" | "failed" | "unknown_outcome";
}

export interface Handoff {
  created_at: string;
  handoff_id: string;
  outcome?: string | null;
  package?: Record<string, unknown>;
  status: "created" | "accepted" | "closed";
}

export interface HandoffCreate {
  conversation_id?: string | null;
  reason?: string | null;
  subject: Handle;
  target: string;
}

export interface HandoffOutcome {
  detail?: Record<string, unknown>;
  outcome: string;
}

export interface OwnershipClaim {
  claim_id: string;
  epoch: number;
  holder: string;
  kind: "owner" | "case" | "task_lock";
  valid_until: string;
}

export interface ShadowRequest {
  days?: number;
}

export interface ShadowRun {
  report_id: string;
  status: "pending" | "done";
}

export interface Suppression {
  channel?: string | null;
  key: string;
  purpose: string;
  reason: string;
  removed?: boolean;
  since: string;
  until?: string | null;
}

export interface SuppressionPage {
  items: Suppression[];
  next_cursor?: string | null;
}

export interface SuppressionSalt {
  salt: string;
  valid_from: string;
}
