// Generated by scripts/sync-spec.ts from spec/openapi/cell.json. Do not edit.
/**
 * Subject signals, the constraints block, the reviewable profile, review requests, legal holds and
 * measurement.
 */

import type { Handle, ObjectRef } from "./common.js";

export interface AttributeEntry {
  apply: "always" | "when_asked";
  category?: string | null;
  confidence: number;
  id: string;
  name: string;
  source: "stated" | "correction" | "acquired" | "kept" | "returned_for_size" | "inferred";
  system?: string | null;
  value: boolean | number | string;
}

export interface AttributionRow {
  agent: string;
  band: "deterministic" | "probable";
  currency: string;
  day: string;
  finality: "provisional" | "final" | "expired_without_outcome";
  lines: number;
  method: "line" | "order" | "identity" | "assisted_handoff";
  outcome: string;
  outcomes: number;
  value_minor: number;
}

/** One method, band and finality over the period: deterministic and probable are never added together. */
export interface AttributionTotal {
  band: "deterministic" | "probable";
  currency: string;
  finality: "provisional" | "final" | "expired_without_outcome";
  lines: number;
  method: "line" | "order" | "identity" | "assisted_handoff";
  outcome: string;
  outcomes: number;
  value_minor: number;
}

/**
 * How often the identity method names the exposure the line's own token names, on the lines where both
 * exist: the confidence of that method in this space.
 */
export interface IdentityCalibration {
  agreeing: number;
  compared: number;
  rate?: number | null;
}

/**
 * Value by day, agent, method and band, deterministic and probable apart; a value is never multiplied by
 * a confidence, and no total adds a probable value to a deterministic one.
 */
export interface AttributionReport {
  identity: IdentityCalibration;
  rows: AttributionRow[];
  since: string;
  totals: AttributionTotal[];
  until: string;
}

/**
 * The company's BI export for the period, as CSV with a header: `order` (the id the company knows the
 * object by), `line` (optional), `value` (in major units, as the signed definition nets it) and
 * `currency`.
 */
export interface BiFile {
  content: string;
  format?: "csv";
}

export interface BlockSubject {
  for?: string;
}

/**
 * A rule of the company delivered in the block, with where it lives and its rank in the order the company
 * declared: the block never ranks two origins by itself.
 */
export interface CompanyRule {
  attr?: string | null;
  id: string;
  op?: "in" | "not_in" | "eq" | "ne" | "lt" | "lte" | "gt" | "gte" | "between" | null;
  /** `code`, `db:<table>`, `prompt:<version>`, `policy:<version>`... */
  origin: string;
  rank: number;
  values?: (boolean | number | string)[];
}

/**
 * Two entries that cannot both hold, and the one that won: the current utterance over what was stated
 * before, and a stated entry over an inferred one. Between two company rules, it is also a data issue.
 */
export interface Conflict {
  by: "current_utterance" | "precedence" | "rule_rank";
  ids: string[];
  kept: string;
}

export interface ConstraintOrigin {
  event_key?: string | null;
  kind: "stated" | "tool_args" | "correction";
  turn_id?: string | null;
}

/** Only what the person said: an inference is never hard. */
export interface HardConstraint {
  attr: string;
  category?: string | null;
  expires_at?: string | null;
  id: string;
  op: "in" | "not_in" | "eq" | "ne" | "lt" | "lte" | "gt" | "gte" | "between";
  origin: ConstraintOrigin;
  relax?: "never" | "ask";
  scope: "turn" | "session" | "persistent";
  source: "stated" | "tool_args" | "correction";
  values: (boolean | number | string)[];
}

/** The block for one tool, through its bindings (`constraints.v0`, rendering). */
export interface Rendered {
  /** Argument values that carry hard constraints and attributes. */
  args: Record<string, unknown>;
  mode: "advisory" | "apply";
  /** Residual ids the SDK filters from the results of an overfetch. */
  post_filter?: string[];
  /** Ids no argument of the tool can express. */
  residual?: string[];
  tool: string;
}

export interface Shown {
  last_at?: string | null;
  ref: string;
  times: number;
}

export interface SoftConstraint {
  attr: string;
  category?: string | null;
  confidence: number;
  id: string;
  polarity?: "prefer" | "avoid";
  source: "inferred" | "stated";
  value: boolean | number | string;
  weight: number;
}

/** What one subject wants, refuses and is, for the tools of this turn (`constraints.v0`). */
export interface ConstraintsBlock {
  already_presented?: Shown[];
  /** Questions the agent should ask, as `for_whom`, before assuming. */
  ask?: string[];
  attributes?: AttributeEntry[];
  conflicts?: Conflict[];
  exclude?: string[];
  hard?: HardConstraint[];
  precedence?: ("current_utterance" | "stated_persistent" | "inferred")[];
  /** What gives way first when a search finds nothing: `soft`, ids. */
  relaxation_order?: string[];
  rendered?: Rendered | null;
  rules?: CompanyRule[];
  soft?: SoftConstraint[];
  subject?: BlockSubject;
  /** A digest of the block, which the turn record cites. */
  version: string;
}

export interface ConstraintsRequest {
  conversation_id?: string | null;
  for?: string;
  subject: Handle;
  /** Rendered for this tool's bindings. */
  tool?: string | null;
}

export interface CounterfactualRun {
  limits?: string[];
  noise_floor?: number | null;
  overlap_at_k?: number | null;
  run_id: string;
}

export interface CounterfactualRunCreate {
  element: string;
  results: (Record<string, unknown>)[];
  tool: string;
}

/**
 * One thing the signals infer about the subject, with what it rests on: the subject can see it, correct
 * it and delete it. What the subject said is not an inference, and is not listed.
 */
export interface Inference {
  /** When its latest evidence happened. */
  at: string;
  /** The field whose value is inferred. */
  attr?: string | null;
  confidence?: number | null;
  /**
   * What it rests on, as counts: effective exposure, weighted signal, events, sessions and lift for a value;
   * times for an interest.
   */
  evidence?: Record<string, unknown>;
  for?: string;
  /** A keyed hash that names the inference; it never carries its value. */
  key: string;
  /**
   * `soft_constraint` when the constraints block carries it as a soft entry, `attribute` for the inferred
   * size, `affinity` for a value with evidence and no entry yet, `interest` for an object.
   */
  kind: "affinity" | "soft_constraint" | "attribute" | "interest";
  /**
   * `interactions`, `implicit_negative` (shown often and never engaged with), or why an interest was kept:
   * `engaged`, `feedback`, `watch`.
   */
  origin: string;
  polarity?: "prefer" | "avoid" | null;
  /** The object of an interest. */
  ref?: string | null;
  /** The purposes it is used for. */
  used_for?: string[];
  value?: boolean | number | string | null;
}

/**
 * The value the subject says instead: a stated preference, or a stated attribute for an inferred size
 * (`source: correction`). The inference it corrects is deleted. An interest is deleted, not corrected.
 */
export interface InferenceCorrection {
  reason?: string | null;
  value: boolean | number | string;
}

export interface InferencePage {
  items: Inference[];
  next_cursor?: string | null;
}

export interface InterleavingReport {
  rows: (Record<string, unknown>)[];
}

export interface LegalHold {
  created_at: string;
  hold_id: string;
  released_at?: string | null;
  scope: "handle" | "object" | "conversation";
  status: "active" | "released";
}

/**
 * Exactly one of `handle`, `object` or `conversation_id`: what is kept from purging while the hold is
 * active.
 */
export interface LegalHoldCreate {
  conversation_id?: string | null;
  handle?: Handle | null;
  object?: ObjectRef | null;
  reason: string;
}

export interface LegalHoldRelease {
  reason: string;
}

/**
 * One outcome attributed to what an agent did, by one method. `line` and `order` are deterministic: the
 * exposure token the order line or the order carried, or the agent's own action on the object.
 * `identity` and `assisted_handoff` are probable: the same item engaged with or shown within a window, or a
 * handoff that assisted the sale. A link carries its line's value whole or none at all: a value is never
 * weighted.
 */
export interface OutcomeLink {
  action_id?: string | null;
  agent?: string | null;
  band: "deterministic" | "probable";
  currency?: string | null;
  exposure_id?: string | null;
  /** When a provisional link becomes final. */
  final_at?: string | null;
  /**
   * `provisional` until the exchange window ends or the object reaches a final state;
   * `expired_without_outcome` when its deadline passed first.
   */
  finality: "provisional" | "final" | "expired_without_outcome";
  handoff_id?: string | null;
  known_at: string;
  line?: string | null;
  link_id: string;
  method: "line" | "order" | "identity" | "assisted_handoff";
  object: string;
  /** The outcome definition of the `measurement` document. */
  outcome: string;
  position?: number | null;
  /** The state the object or its line is in. */
  state: string;
  turn_id?: string | null;
  /** When the outcome first counted. */
  valid_at: string;
  /** In the currency's minor units; absent: none. */
  value_minor?: number | null;
}

export interface OutcomePage {
  items: OutcomeLink[];
  next_cursor?: string | null;
}

export interface PowerRequest {
  alpha?: number;
  effect: number;
  metric: string;
  power?: number;
}

export interface PowerResult {
  days: number | null;
  sample_size: number | null;
}

export interface ReconcileRequest {
  file: BiFile;
  since: string;
  until: string;
}

export interface ReconciledLine {
  bi_minor: number;
  line: string;
  order: string;
  ours_minor: number;
}

/**
 * Our value of each line against the BI's, on the lines both know; lines only one side knows are
 * counted apart and never enter the deviation.
 */
export interface ReconcileResult {
  bi_minor: number;
  currency?: string | null;
  /** |ours - BI| / BI on the lines both know. */
  deviation: number | null;
  matched: number;
  only_bi: number;
  only_ours: number;
  ours_minor: number;
  report_id: string;
  tolerance: number;
  within_tolerance: boolean;
  /** The lines that differ most. */
  worst?: ReconciledLine[];
}

export interface ReviewRequest {
  created_at: string;
  decision_receipt_id?: string | null;
  /**
   * Built from receipts: their ids, kinds, surfaces, rules, versions and inputs by reference, never personal
   * content.
   */
  explanation?: Record<string, unknown>;
  outcome?: "upheld" | "reversed" | "corrected" | null;
  profile_id: string;
  reason?: string | null;
  request_id: string;
  /** The reviewer's note. */
  resolution?: string | null;
  resolved_at?: string | null;
  status: "open" | "resolved";
}

/** A request to review an automated decision, sent to the controller's data protection officer. */
export interface ReviewRequestCreate {
  /** The receipt of the decision; absent, the subject's recent decisions. */
  decision_receipt_id?: string | null;
  reason: string;
}

export interface ReviewRequestPage {
  items: ReviewRequest[];
  next_cursor?: string | null;
}

export interface ReviewResolution {
  note?: string | null;
  outcome: "upheld" | "reversed" | "corrected";
}

export interface UnmetDemandPage {
  items: (Record<string, unknown>)[];
  next_cursor?: string | null;
}
