// Generated by scripts/sync-spec.ts from spec/openapi/cell.json. Do not edit.
/**
 * Subject signals, the constraints block, the reviewable profile, review requests, legal holds and
 * measurement.
 */

import type { Handle, ObjectRef } from "./common.js";

/**
 * One arm against `control` on one metric, adjusted by CUPED when the history varies, with the mixture
 * sequential test: its p-value and interval hold at any look, so the report may be read every day.
 */
export interface ArmComparison {
  arm: string;
  arm_mean: number;
  ci_high: number;
  /** The always-valid interval of `difference` at the test's `alpha`. */
  ci_low: number;
  /** Per person, before the adjustment. */
  control_mean: number;
  /** `p_value` at or below `alpha`: the difference is real. */
  decided: boolean;
  /** The arm minus the control, per person, adjusted. */
  difference: number;
  /** The daily looks kept before this one. */
  looks: number;
  metric: "conversion" | "value";
  /** The running minimum over the daily looks and this one. */
  p_value: number;
  /** `difference` over the control's mean. */
  relative: number | null;
  /** The share of the variance CUPED removed; absent when it did not apply. */
  variance_reduction: number | null;
}

/** The people one arm holds and what they did after they were assigned, from the outcome links. */
export interface ArmOutcomes {
  arm: string;
  /** People with an outcome in a success state. */
  converted: number;
  outcomes: number;
  people: number;
  /** Their lines' money, each line once whatever the method. */
  value_minor: number;
}

export interface AskedAttribute {
  attr: string;
  op: "in" | "not_in" | "eq" | "ne" | "lt" | "lte" | "gt" | "gte" | "between";
  values: (boolean | number | string)[];
}

export interface AttributeEntry {
  apply: "always" | "when_asked";
  category?: string | null;
  confidence: number;
  id: string;
  name: string;
  source: "stated" | "correction" | "acquired" | "kept" | "returned_for_size" | "inferred";
  system?: string | null;
  value: boolean | number | string;
}

export interface AttributionRow {
  agent: string;
  band: "deterministic" | "probable";
  currency: string;
  day: string;
  finality: "provisional" | "final" | "expired_without_outcome";
  lines: number;
  method: "line" | "order" | "identity" | "assisted_handoff";
  outcome: string;
  outcomes: number;
  value_minor: number;
}

/** One method, band and finality over the period: deterministic and probable are never added together. */
export interface AttributionTotal {
  band: "deterministic" | "probable";
  currency: string;
  finality: "provisional" | "final" | "expired_without_outcome";
  lines: number;
  method: "line" | "order" | "identity" | "assisted_handoff";
  outcome: string;
  outcomes: number;
  value_minor: number;
}

/**
 * How often the identity method names the exposure the line's own token names, on the lines where both
 * exist: the confidence of that method in this space.
 */
export interface IdentityCalibration {
  agreeing: number;
  compared: number;
  rate?: number | null;
}

/**
 * Value by day, agent, method and band, deterministic and probable apart; a value is never multiplied by
 * a confidence, and no total adds a probable value to a deterministic one.
 */
export interface AttributionReport {
  identity: IdentityCalibration;
  rows: AttributionRow[];
  since: string;
  totals: AttributionTotal[];
  until: string;
}

/**
 * The company's BI export for the period, uploaded first (`POST /v1/measure/reconcile/uploads`), as CSV
 * with a header: `order` (the id the company knows the object by), `line` (optional), `value` (in major
 * units, as the signed definition nets it) and `currency`. It is read once and deleted.
 */
export interface BiFile {
  format?: "csv";
  upload_id: string;
}

export interface BiUpload {
  expires_at: string;
  /** Send exactly these headers; the storage refuses other bytes. */
  upload_headers?: Record<string, string>;
  upload_id: string;
  upload_url: string;
}

/** Reserves the upload of the company's BI file: its size and SHA-256, which the storage checks. */
export interface BiUploadRequest {
  sha256: string;
  size_bytes: number;
}

export interface BlockSubject {
  for?: string;
}

/**
 * A rule of the company delivered in the block, with where it lives and its rank in the order the company
 * declared: the block never ranks two origins by itself.
 */
export interface CompanyRule {
  attr?: string | null;
  id: string;
  op?: "in" | "not_in" | "eq" | "ne" | "lt" | "lte" | "gt" | "gte" | "between" | null;
  /** `code`, `db:<table>`, `prompt:<version>`, `policy:<version>`... */
  origin: string;
  rank: number;
  values?: (boolean | number | string)[];
}

/**
 * Two entries that cannot both hold, and the one that won: the current utterance over what was stated
 * before, and a stated entry over an inferred one. Between two company rules, it is also a data issue.
 */
export interface Conflict {
  by: "current_utterance" | "precedence" | "rule_rank";
  ids: string[];
  kept: string;
}

export interface ConstraintOrigin {
  event_key?: string | null;
  kind: "stated" | "tool_args" | "correction";
  turn_id?: string | null;
}

/** Only what the person said: an inference is never hard. */
export interface HardConstraint {
  attr: string;
  category?: string | null;
  expires_at?: string | null;
  id: string;
  op: "in" | "not_in" | "eq" | "ne" | "lt" | "lte" | "gt" | "gte" | "between";
  origin: ConstraintOrigin;
  relax?: "never" | "ask";
  scope: "turn" | "session" | "persistent";
  source: "stated" | "tool_args" | "correction";
  values: (boolean | number | string)[];
}

/** The block for one tool, through its bindings (`constraints.v0`, rendering). */
export interface Rendered {
  /** Argument values that carry hard constraints and attributes. */
  args: Record<string, unknown>;
  mode: "advisory" | "apply";
  /** Residual ids the SDK filters from the results of an overfetch. */
  post_filter?: string[];
  /** Ids no argument of the tool can express. */
  residual?: string[];
  tool: string;
}

export interface Shown {
  last_at?: string | null;
  ref: string;
  times: number;
}

export interface SoftConstraint {
  attr: string;
  category?: string | null;
  confidence: number;
  id: string;
  polarity?: "prefer" | "avoid";
  source: "inferred" | "stated";
  value: boolean | number | string;
  weight: number;
}

/** What one subject wants, refuses and is, for the tools of this turn (`constraints.v0`). */
export interface ConstraintsBlock {
  already_presented?: Shown[];
  /** Questions the agent should ask, as `for_whom`, before assuming. */
  ask?: string[];
  attributes?: AttributeEntry[];
  conflicts?: Conflict[];
  exclude?: string[];
  hard?: HardConstraint[];
  precedence?: ("current_utterance" | "stated_persistent" | "inferred")[];
  /** What gives way first when a search finds nothing: `soft`, ids. */
  relaxation_order?: string[];
  rendered?: Rendered | null;
  rules?: CompanyRule[];
  soft?: SoftConstraint[];
  subject?: BlockSubject;
  /**
   * The block as lines for a model, in the space's language, each field by its label and each operator in
   * words; the SDK places it beside the state view's text. Not part of `version`.
   */
  text?: string | null;
  /** A digest of the block, which the turn record cites. */
  version: string;
}

export interface ConstraintsRequest {
  conversation_id?: string | null;
  for?: string;
  subject: Handle;
  /** Rendered for this tool's bindings. */
  tool?: string | null;
}

/**
 * An item the person engaged with in the recorded turn, by its 1-based position in each live list;
 * absent where the list does not hold it.
 */
export interface CounterfactualEngaged {
  base?: number | null;
  variant?: number | null;
}

/**
 * One recorded tool call run live three times at the same moment: twice with the element (the base,
 * whose two lists measure the tool's own noise) and once without it (the variant). Positions and
 * overlaps only: never an item, an argument or a result.
 */
export interface CounterfactualCase {
  /** Items in the base's first list. */
  base_count?: number | null;
  call_id: string;
  /** The calls ran as the tool's dry run. */
  dry_run?: boolean;
  engaged?: CounterfactualEngaged[];
  /** The positions compared: the recorded list's `visible_k`, else the run's `k`. */
  k?: number | null;
  /** overlap@k of the base's two lists: the tool's own noise. */
  noise?: number | null;
  /** overlap@k of the base's first list and the variant's. */
  overlap?: number | null;
  /**
   * `no_dry_run` for a tool that writes state and has no dry run: it is never called. `tool_error` when a
   * call failed, `infrastructure_error` when the runner could not run the case.
   */
  status: "completed" | "no_dry_run" | "tool_error" | "infrastructure_error";
  turn_id: string;
  /** Items in the variant's list. */
  variant_count?: number | null;
}

/** Where the items the person engaged with went without the element, over the completed cases. */
export interface CounterfactualEngagement {
  /** Within the variant's first `k` and not the base's. */
  gained: number;
  items: number;
  /** Within the first `k` of both lists. */
  kept: number;
  /** Within the base's first `k` and not the variant's. */
  lost: number;
  /**
   * The variant's position minus the base's, averaged over the items both lists hold; positive when they
   * fell.
   */
  mean_shift?: number | null;
  /** Within the first `k` of the base's list. */
  shown: number;
}

/**
 * Whether the element changes what the tool returns, beyond the tool's own noise. It never says whether
 * the result got better, nor how the model reacts: `limits` says so, and what else holds the answer
 * back.
 */
export interface CounterfactualRun {
  above_noise: number;
  /** Completed cases whose overlap is below their own noise. */
  below_noise: number;
  cases: number;
  completed: number;
  created_at: string;
  /** `noise_floor - overlap`: how much of the first positions the element moves beyond noise. */
  effect: number | null;
  element: "constraints" | "hard" | "size" | "exclude";
  engaged: CounterfactualEngagement;
  label?: string | null;
  limits: ("not_quality" | "model_reaction_not_measured" | "trivial_for_hard" | "few_cases" | "noisy_tool" | "cases_skipped" | "dry_run")[];
  /** Mean overlap@k of the base with itself. */
  noise_floor: number | null;
  /** Mean overlap@k of the base and the variant. */
  overlap: number | null;
  /**
   * The two-sided sign test of `below_noise` against `above_noise`: how likely a split this uneven is when
   * the element changes nothing.
   */
  p_value: number | null;
  run_id: string;
  /** The cases not completed. */
  skipped?: Record<string, number>;
  ties: number;
  tool: string;
}

/**
 * What a runner measured in the company's CI for one tool and one element (the tool counterfactual
 * spec).
 */
export interface CounterfactualRunCreate {
  cases: CounterfactualCase[];
  element: "constraints" | "hard" | "size" | "exclude";
  /** The positions compared when a recorded list has no `visible_k`. */
  k?: number;
  /** A name for the run, such as the commit or the build it ran on. */
  label?: string | null;
  tool: string;
}

export interface CounterfactualRunPage {
  items: CounterfactualRun[];
  next_cursor?: string | null;
}

export interface ExperimentResult {
  agent?: string | null;
  alpha: number;
  arms: ArmOutcomes[];
  /** Empty until each arm holds enough people for the normal approximation. */
  comparisons: ArmComparison[];
  /** The days before each person's assignment taken as the covariate. */
  cuped_days: number;
  element?: string | null;
  ends_at?: string | null;
  experiment: string;
  kind: "element" | "agent";
  starts_at: string;
}

/**
 * Every experiment on an element or an agent, arm by arm, from what people did after they were assigned:
 * incremental, as only a holdout says.
 */
export interface ExperimentReport {
  as_of: string;
  experiments: ExperimentResult[];
}

/**
 * One thing the signals infer about the subject, with what it rests on: the subject can see it, correct
 * it and delete it. What the subject said is not an inference, and is not listed.
 */
export interface Inference {
  /** When its latest evidence happened. */
  at: string;
  /** The field whose value is inferred. */
  attr?: string | null;
  confidence?: number | null;
  /**
   * What it rests on, as counts: effective exposure, weighted signal, events, sessions and lift for a value;
   * times for an interest.
   */
  evidence?: Record<string, unknown>;
  for?: string;
  /** A keyed hash that names the inference; it never carries its value. */
  key: string;
  /**
   * `soft_constraint` when the constraints block carries it as a soft entry, `attribute` for the inferred
   * size, `affinity` for a value with evidence and no entry yet, `interest` for an object.
   */
  kind: "affinity" | "soft_constraint" | "attribute" | "interest";
  /**
   * `interactions`, `implicit_negative` (shown often and never engaged with), or why an interest was kept:
   * `engaged`, `feedback`, `watch`.
   */
  origin: string;
  polarity?: "prefer" | "avoid" | null;
  /** The object of an interest. */
  ref?: string | null;
  /** The purposes it is used for. */
  used_for?: string[];
  value?: boolean | number | string | null;
}

/**
 * The value the subject says instead: a stated preference, or a stated attribute for an inferred size
 * (`source: correction`). The inference it corrects is deleted. An interest is deleted, not corrected.
 */
export interface InferenceCorrection {
  reason?: string | null;
  value: boolean | number | string;
}

export interface InferencePage {
  items: Inference[];
  next_cursor?: string | null;
}

export interface InterleavingRow {
  day: string;
  experiment: string;
  impressions: number;
  /** Impressions engaged with equally, or not at all. */
  ties: number;
  tool: string;
  /** Impressions whose engagement went to the items ranking `a` contributed. */
  wins_a: number;
  wins_b: number;
}

export interface InterleavingTotal {
  experiment: string;
  impressions: number;
  /** The two-sided sign test on the decided impressions; absent before any was decided. */
  p_value: number | null;
  ties: number;
  tool: string;
  wins_a: number;
  wins_b: number;
}

/**
 * Interleaved lists of a tool's two rankings (team draft, seeded by the turn): which ranking the
 * person's engagement credited, impression by impression, by day and over the period.
 */
export interface InterleavingReport {
  rows: InterleavingRow[];
  since: string;
  totals: InterleavingTotal[];
  until: string;
}

export interface LegalHold {
  created_at: string;
  hold_id: string;
  released_at?: string | null;
  scope: "handle" | "object" | "conversation";
  status: "active" | "released";
}

/**
 * Exactly one of `handle`, `object` or `conversation_id`: what is kept from purging while the hold is
 * active.
 */
export interface LegalHoldCreate {
  conversation_id?: string | null;
  handle?: Handle | null;
  object?: ObjectRef | null;
  reason: string;
}

export interface LegalHoldRelease {
  reason: string;
}

/**
 * One outcome attributed to what an agent did, by one method. `line` and `order` are deterministic: the
 * exposure token the order line or the order carried, or the agent's own action on the object.
 * `identity` and `assisted_handoff` are probable: the same item engaged with or shown within a window, or a
 * handoff that assisted the sale. A link carries its line's value whole or none at all: a value is never
 * weighted.
 */
export interface OutcomeLink {
  action_id?: string | null;
  agent?: string | null;
  band: "deterministic" | "probable";
  /**
   * Of an `identity` link: how often that method names the exposure a line's own token names in this space,
   * where both exist. Beside the value, never multiplied by it.
   */
  confidence?: number | null;
  currency?: string | null;
  exposure_id?: string | null;
  /** When a provisional link becomes final. */
  final_at?: string | null;
  /**
   * `provisional` until the exchange window ends or the object reaches a final state;
   * `expired_without_outcome` when its deadline passed first.
   */
  finality: "provisional" | "final" | "expired_without_outcome";
  handoff_id?: string | null;
  known_at: string;
  line?: string | null;
  link_id: string;
  method: "line" | "order" | "identity" | "assisted_handoff";
  object: string;
  /** The outcome definition of the `measurement` document. */
  outcome: string;
  position?: number | null;
  /** The state the object or its line is in. */
  state: string;
  turn_id?: string | null;
  /** When the outcome first counted. */
  valid_at: string;
  /** In the currency's minor units; absent: none. */
  value_minor?: number | null;
}

export interface OutcomePage {
  items: OutcomeLink[];
  next_cursor?: string | null;
}

/**
 * How long the space's traffic takes to detect a difference of `effect` (relative: 0.1 is 10%) on
 * `metric`. The traffic and the baseline come from the space's history, the named experiment's or the
 * busiest one's of the last 28 days, unless given.
 */
export interface PowerRequest {
  alpha?: number;
  /** Per person: a rate for `conversion`, minor units for `value`. */
  baseline_mean?: number | null;
  /** Per person, for `value`; a rate's follows from its mean. */
  baseline_sd?: number | null;
  control_fraction?: number;
  /** New people a day entering the test. */
  daily_people?: number | null;
  /** The relative difference to detect: 0.1 is 10%. */
  effect: number;
  /** The experiment whose history to use. */
  experiment?: string | null;
  metric?: "conversion" | "value";
  power?: number;
}

export interface PowerResult {
  baseline_from: "given" | "history";
  baseline_mean: number;
  baseline_sd: number;
  daily_people: number;
  /** At a fixed horizon, looked at once, at the end. */
  days: number | null;
  days_sequential: number | null;
  effect: number;
  /** The experiment whose history was used. */
  experiment?: string | null;
  metric: "conversion" | "value";
  /** Both arms together, at a fixed horizon. */
  people: number | null;
  /** Both arms together, for the daily-looked sequential test to have decided with `power`. */
  people_sequential: number | null;
  traffic_from: "given" | "history";
}

export interface ReconcileRequest {
  file: BiFile;
  since: string;
  until: string;
}

export interface ReconciledLine {
  bi_minor: number;
  line: string;
  order: string;
  ours_minor: number;
}

/**
 * Our value of each line against the BI's, on the lines both know; lines only one side knows are
 * counted apart and never enter the deviation.
 */
export interface ReconcileResult {
  bi_minor: number;
  currency?: string | null;
  /** |ours - BI| / BI on the lines both know. */
  deviation: number | null;
  matched: number;
  only_bi: number;
  only_ours: number;
  ours_minor: number;
  report_id: string;
  tolerance: number;
  within_tolerance: boolean;
  /** The lines that differ most. */
  worst?: ReconciledLine[];
}

export interface ReviewRequest {
  created_at: string;
  decision_receipt_id?: string | null;
  /**
   * Built from receipts: their ids, kinds, surfaces, rules, versions and inputs by reference, never personal
   * content.
   */
  explanation?: Record<string, unknown>;
  outcome?: "upheld" | "reversed" | "corrected" | null;
  profile_id: string;
  reason?: string | null;
  request_id: string;
  /** The reviewer's note. */
  resolution?: string | null;
  resolved_at?: string | null;
  status: "open" | "resolved";
}

/** A request to review an automated decision, sent to the controller's data protection officer. */
export interface ReviewRequestCreate {
  /** The receipt of the decision; absent, the subject's recent decisions. */
  decision_receipt_id?: string | null;
  reason: string;
}

export interface ReviewRequestPage {
  items: ReviewRequest[];
  next_cursor?: string | null;
}

export interface ReviewResolution {
  note?: string | null;
  outcome: "upheld" | "reversed" | "corrected";
}

/**
 * One combination people asked a tool for, in one week, that came back with nothing or with fewer than
 * three results. Never a person: a combination fewer than the space's minimum of people asked is left
 * out.
 */
export interface UnmetDemand {
  /**
   * What the tool's arguments asked, on the type registry's fields, values normalized; empty when the
   * arguments named none.
   */
  asked: AskedAttribute[];
  calls: number;
  /** Calls that returned nothing; the rest returned one or two results. */
  empty: number;
  /** Distinct people who asked it that week. */
  people: number;
  tool: string;
  /** The Monday the week starts on. */
  week: string;
}

export interface UnmetDemandPage {
  items: UnmetDemand[];
  min_people: number;
  next_cursor?: string | null;
  since: string;
  until: string;
}
