// Generated by scripts/sync-spec.ts from spec/openapi/cell.json. Do not edit.
/**
 * Subject signals, the constraints block, the reviewable profile, review requests, legal holds and
 * measurement.
 *
 * Draft: the server has not fixed these types yet, and their fields may still change.
 */

import type { Handle, ObjectRef } from "./common.js";

/** Value by method and band, deterministic and probable apart; weights are never summed as money. */
export interface AttributionReport {
  rows: (Record<string, unknown>)[];
  since: string;
  until: string;
}

/** The `constraints.v0` block. */
export interface ConstraintsBlock {
  already_presented?: (Record<string, unknown>)[];
  ask?: string[];
  attributes?: (Record<string, unknown>)[];
  exclude?: string[];
  hard?: (Record<string, unknown>)[];
  precedence?: string | null;
  relaxation_order?: string[];
  rendered?: Record<string, unknown> | null;
  rules?: (Record<string, unknown>)[];
  soft?: (Record<string, unknown>)[];
  subject: Record<string, unknown>;
  version: string;
}

export interface ConstraintsRequest {
  conversation_id?: string | null;
  for?: string;
  subject: Handle;
  /** Rendered for this tool's bindings. */
  tool?: string | null;
}

export interface CounterfactualRun {
  limits?: string[];
  noise_floor?: number | null;
  overlap_at_k?: number | null;
  run_id: string;
}

export interface CounterfactualRunCreate {
  element: string;
  results: (Record<string, unknown>)[];
  tool: string;
}

export interface Inference {
  at: string;
  confidence?: number | null;
  evidence?: Record<string, unknown>;
  key: string;
  kind: "affinity" | "soft_constraint" | "attribute" | "interest";
  origin: string;
  used_for?: string[];
}

/** Becomes a stated preference (`source: correction`). */
export interface InferenceCorrection {
  reason?: string | null;
  value: unknown;
}

export interface InferencePage {
  items: Inference[];
  next_cursor?: string | null;
}

export interface InterleavingReport {
  rows: (Record<string, unknown>)[];
}

export interface LegalHold {
  created_at: string;
  hold_id: string;
  released_at?: string | null;
  status: "active" | "released";
}

export interface LegalHoldCreate {
  conversation_id?: string | null;
  handle?: Handle | null;
  object?: ObjectRef | null;
  reason: string;
}

export interface LegalHoldRelease {
  reason: string;
}

export interface OutcomePage {
  items: (Record<string, unknown>)[];
  next_cursor?: string | null;
}

export interface PowerRequest {
  alpha?: number;
  effect: number;
  metric: string;
  power?: number;
}

export interface PowerResult {
  days: number | null;
  sample_size: number | null;
}

export interface ReconcileRequest {
  since: string;
  until: string;
  upload_ref: string;
}

export interface ReconcileResult {
  detail?: Record<string, unknown>;
  deviation: number;
}

export interface ReviewRequest {
  created_at: string;
  profile_id: string;
  request_id: string;
  resolution?: string | null;
  status: "open" | "resolved";
}

/** A request to review an automated decision (LGPD, art. 20), sent to the controller's DPO. */
export interface ReviewRequestCreate {
  decision_receipt_id?: string | null;
  reason: string;
}

export interface ReviewRequestPage {
  items: ReviewRequest[];
  next_cursor?: string | null;
}

export interface ReviewResolution {
  note?: string | null;
  outcome: "upheld" | "reversed" | "corrected";
}

export interface UnmetDemandPage {
  items: (Record<string, unknown>)[];
  next_cursor?: string | null;
}
