// Generated by scripts/sync-spec.ts from spec/openapi/cell.json. Do not edit.
/**
 * Typed state: objects a system of record pushes, reads with a purpose, the agent's working state and the SDK
 * profile.
 */

import type { Handle } from "./common.js";

/**
 * What happens to a claim that does not stand, by the task's context (an output kind or a document kind);
 * `default` for any other. A context the contract lists as immutable is never rewritten.
 */
export interface Actions {
  contexts?: Record<string, "block" | "warn" | "count" | "rewrite_if_unequivocal" | "discard_anchor_and_count">;
  default: "block" | "warn" | "count" | "rewrite_if_unequivocal" | "discard_anchor_and_count";
  /** The caveat a blocked passage gives way to, in a mutable output. */
  replace_with?: string | null;
}

export interface AgentState {
  body?: Record<string, unknown>;
  updated_at?: string | null;
  version: number;
}

/** One working state of a customer, as the Console shows it: never its content. */
export interface AgentStateMeta {
  agent: string;
  /** The size of the state's body. */
  bytes: number;
  schema_version?: string | null;
  scope_kind: "conversation" | "task" | "object" | "subject";
  source_id: string;
  updated_at: string;
  valid_until: string;
  version: number;
}

export interface AgentStateMetaPage {
  items: AgentStateMeta[];
}

/**
 * What one working state belongs to. The id travels in the body, never in a URL: a conversation id may
 * look like a phone number.
 */
export interface AgentStateScope {
  id: string;
  kind: "conversation" | "task" | "object" | "subject";
}

export interface AgentStateReadRequest {
  agent: string;
  scope: AgentStateScope;
}

/**
 * A write of an agent's working state, by its code and never by a model: `cas` replaces the whole state
 * at `if_version` (0 when it must not exist yet); `merge_by_key` replaces each top-level field it names and
 * removes a field written as exactly `{"$delete": true}`.
 */
export interface AgentStateWrite {
  agent: string;
  body: Record<string, unknown>;
  if_version?: number | null;
  mode: "cas" | "merge_by_key";
  scope: AgentStateScope;
  /**
   * The customer the state is about, when its scope does not name them: erasing the customer and their data
   * package find the state by it.
   */
  subject?: Handle | null;
}

export interface AgentStateWriteResult {
  reason?: "over_cap" | "not_declared_field" | null;
  stored: boolean;
  version: number;
}

export interface AnchorEvidence {
  /** Counted apart: law and fact never add up. */
  coverage: "fact" | "law";
  min_match?: number;
}

export interface Negation {
  /** The argument that takes the values the field must not have. */
  param: string;
}

/**
 * One argument of the tool and the field it carries. `in` and `eq` render to `param`, `not_in` and `ne`
 * to the negation's, and a comparison or `between` only when `ops` lists it.
 */
export interface BoundArg {
  /** The field, as `type.field`. */
  attr: string;
  negation?: Negation | null;
  ops?: ("in" | "not_in" | "eq" | "ne" | "lt" | "lte" | "gt" | "gte" | "between")[];
  param: string;
  /** The case text is sent in. */
  transform?: "lower" | "upper" | null;
}

/** An object of the type registry: a subject's or a shared one, whose key may name a variant. */
export interface StateRef {
  id: string;
  namespace: string;
  type: string;
  variant?: string | null;
}

/** A field of an interest whose value is not the one the subject was shown. */
export interface ChangeSinceSeen {
  field: string;
  now?: unknown;
  /** When the source observed the value now held. */
  observed_at?: string | null;
  ref: StateRef;
  seen?: unknown;
}

/** A value in the turn record, from a tool's result or from state, that the number is checked against. */
export interface ValueEvidence {
  /** The value is within its type's `claim_max_age`, or the claim is `stale`. */
  fresh_for?: "claim" | null;
  /** The words that state each declared gap; a gap without them is stated by its name. */
  gap_terms?: Record<string, string[]>;
  /** The value's declared gaps must be said with it, or `gap_not_stated`. */
  must_state_gaps?: boolean;
  /** The value's role is the number's role. */
  same_role?: boolean;
  type?: string | null;
  /** A field or a computed value of `type`. */
  value?: string | null;
}

/** What the turn record must hold for a claim of the category to stand: exactly one kind. */
export interface ClaimEvidence {
  anchor?: AnchorEvidence | null;
  /** A call of this tool in the turn. */
  tool?: string | null;
  tool_any?: string[];
  value?: ValueEvidence | null;
}

/**
 * How a category finds its claims in the text, without a model: numbers of these classes, the words
 * around them that give their role, terms of the trade, named patterns, or sections of a document.
 */
export interface Detect {
  classes?: ("money" | "percent" | "date" | "duration" | "quantity" | "count" | "dosage")[];
  document_sections?: string[];
  patterns?: ("article_citation" | "precedent_citation")[];
  /** The words that give a number its role, synonyms and every language in one list. */
  roles?: Record<string, string[]>;
  /** With `classes`, a number counts only in a sentence that holds one of them; alone, the term is the claim. */
  terms?: string[];
}

/**
 * How a number is handled by where it came from: computed (a value with provenance in the turn, by rule
 * or observed) is checked against it; quoted (inside quotation marks) is checked only for being in a source,
 * as written, even when it is false; said by the model (no origin) takes this action, or the category's.
 */
export interface Natures {
  computed?: "check" | "count";
  model?: "block" | "warn" | "count" | null;
  quoted?: "verbatim" | "count";
}

export interface ClaimCategory {
  actions: Actions;
  /** Empty: every agent. */
  agents?: string[];
  detect: Detect;
  evidence: ClaimEvidence;
  id: string;
  natures?: Natures;
}

export interface ClaimOutputs {
  immutable?: string[];
  mutable?: string[];
}

/**
 * Fingerprints of the company's own prompt: hashes of every `n` words, computed by the SDK, never the
 * prompt itself. An output that repeats one gives way to `redact`, recorded as a claim of the category
 * `internal_text` with the verdict `internal_text_found`, the action taken and, as evidence, the
 * `shingle_hashes_ref` in `document`.
 */
export interface InternalText {
  n?: number;
  redact: string;
  /** The prompt version the hashes were computed from. */
  shingle_hashes_ref: string;
}

/**
 * The contract as the SDK keeps it: everything but the negative corpus's phrases, which only the CI's
 * `niadra contract test` reads, from the company's own copy.
 */
export interface ClaimContractSummary {
  categories?: ClaimCategory[];
  internal_text?: InternalText | null;
  languages: ("pt" | "en" | "es")[];
  negative_corpus_version?: string | null;
  outputs?: ClaimOutputs;
  version: string;
}

/** A content field whose text Niadra does not hold (`pointer`, `hash_only`), or holds under scan. */
export interface ContentMarker {
  mode: "full" | "pointer" | "hash_only";
  /** Where the SDK reads the text inside the company's boundary. */
  pointer?: string | null;
  scan: "pending" | "clean" | "flagged";
  sha256?: string | null;
}

export interface ContentRelease {
  reason: string;
}

export interface ContentReleaseResult {
  released: boolean;
}

/**
 * A field the type derives from the related objects of one relation (a look's pieces), computed at this
 * read and never stored. A related object whose data is not known leaves it `unobserved`, unless the answer
 * is already decided.
 */
export interface DerivedState {
  logic: "yes" | "no" | "unobserved";
  /** The related objects it was computed over. */
  over: number;
  /**
   * When it is not `yes`, the related objects, as `type:namespace:id`, that kept it from `yes`: for `all` and
   * `any` the ones the condition does not hold for or that are not known, for `count`, `min` and `max` the
   * ones not known. In the relation's order, the first 10.
   */
  pieces_out?: string[];
  /**
   * How many of them were not known: out of the working set, not an exact match (`status_field`), or with the
   * data the condition reads not observed.
   */
  unknown: number;
  v?: unknown;
}

/**
 * What changed between the declaration and the type the schema proposes now, as counts: never a new name,
 * a value or a definition (object-type spec, 8.8.2).
 */
export interface DriftChanges {
  /** The declaration's fields removed or retyped, and its state field when the states differ. */
  fields?: string[];
  fields_added: number;
  fields_removed: number;
  fields_retyped: number;
  key_changed: boolean;
  relations_added: number;
  relations_removed: number;
  states_added: number;
  states_removed: number;
}

/**
 * The agent features a space turns on: everything is off until the space's `features`
 * document lists it, and `GET /v1/sdk/profile` announces what is on.
 */
export type Feature = "turns" | "state" | "agent_state" | "signals" | "claims" | "coordination" | "measurement" | "notifications" | "legal_holds";

export interface FieldCoverage {
  /** The median age, in seconds, of the field's newest observation. */
  age_p50_s?: number | null;
  /** The share of the type's objects some source observed the field of. */
  coverage: number;
  field: string;
}

/** A field's value before its latest change, kept for the fields that declare `track_changes`. */
export interface PreviousValue {
  logic: "yes" | "no" | "unobserved" | "known_defect";
  v?: unknown;
}

/**
 * One field as a read serves it: the value with its logical value, stamps, source and observer, and the
 * freshness computed now against the type's current rule.
 */
export interface FieldState {
  /** Seconds since `observed_at`. */
  age_s?: number | null;
  claim_safe: boolean;
  completeness?: string | null;
  content?: ContentMarker | null;
  /** When Niadra first knew it; never moves. */
  known_at?: string | null;
  logic: "yes" | "no" | "unobserved" | "known_defect";
  /** The reader's access masks the value: `v` is absent. */
  masked?: boolean;
  /** When the source observed the value. */
  observed_at?: string | null;
  observer?: string | null;
  role?: string | null;
  src?: string | null;
  status: "fresh" | "stale" | "expired";
  v?: unknown;
  valid_at?: string | null;
  was?: PreviousValue | null;
}

/** One row of what people and agents said about an object, kept under the person who said it. */
export interface SaidAbout {
  attr?: string | null;
  /**
   * `shared` reaches every participant of the object, a customer-facing agent included; `internal`, the
   * internal readers only.
   */
  audience: "shared" | "internal";
  /** The handle of who said it; only in the Console. */
  by?: string | null;
  /** Always false: what was said may be reported as said, never stated as the record. */
  claim_safe?: false;
  /** The value said differs from the one recorded: a data issue was opened. */
  diverges?: boolean;
  due_at?: string | null;
  expires_at?: string | null;
  /** The fact, open item or instruction it is. */
  id: string;
  item_kind?: "promise" | "dispute" | "request" | null;
  kind: "observation" | "item" | "instruction";
  /**
   * The field of the object's type an observation is about: shown beside the value the system of record
   * holds, never in its place.
   */
  observes?: string | null;
  overdue?: boolean;
  predicate?: string | null;
  /** The value the system of record holds for `observes`. */
  recorded?: unknown;
  /** The role of who said it on the object (`owner`, `participant`, `lawyer`). */
  role?: string | null;
  said_at: string;
  strength?: "must" | "must_not" | null;
  text: string;
}

/**
 * What the owner and participants of an object said about it (memory bound to the object), newest
 * first, at most 20 of each kind, as this reader may read it.
 */
export interface ObjectMemoryOut {
  /** What must or must not be done about the object. */
  instructions?: SaidAbout[];
  /** Promises, disputes and requests about the object still open. */
  items?: SaidAbout[];
  /** Observations about the object. */
  said?: SaidAbout[];
}

export interface OutcomeState {
  at?: string | null;
  final: boolean;
  /** A canonical state of the type, or `expired_without_outcome`. */
  state: string;
}

/**
 * A named reading's value, as niadra-expr computes it: the logical value, and the kind and value when
 * known (dates as `YYYY-MM-DD`, times in UTC, durations in milliseconds).
 */
export interface ReadingResult {
  absent?: string | null;
  /**
   * For a reading that includes its inputs: the derived object's inputs, by the name its type gives them, as
   * `type:namespace:id`.
   */
  inputs?: Record<string, string> | null;
  logic: "yes" | "no" | "unobserved" | "known_defect";
  type?: "bool" | "number" | "string" | "duration" | "date" | "datetime" | "list" | null;
  v?: unknown;
}

export interface Refetch {
  admitted: boolean;
  priority: "high" | "normal" | "low";
  reason: string;
}

export interface Refusal {
  action?: string | null;
  reason: string;
}

export interface TimerState {
  /** Computed now from the rule and the values. */
  due_at?: string | null;
  fired_at?: string | null;
  name: string;
  state: "armed" | "fired" | "cancelled";
  /**
   * The firing this one replaces: a timer that already fired fires again once the value that armed it is
   * revised.
   */
  supersedes_firing_id?: string | null;
}

/** A value the company computed, kept as a versioned fact with the rule that produced it. */
export interface ValueState {
  /** The name of the absence, when absent. */
  absent_as?: string | null;
  claim_safe: boolean;
  computed_at: string;
  declared_gaps?: string[];
  gap_effect?: "errs_early" | "errs_late" | "unknown";
  logic: "yes" | "no" | "unobserved" | "known_defect";
  rule: string;
  status: "fresh" | "stale" | "expired";
  supersedes_version?: number | null;
  v?: unknown;
  version: number;
}

/**
 * One object as a state read serves it: fields with four logical values and their stamps, computed
 * values, lifecycle, timers and readings, and what may not be claimed with data this old. A read never
 * refuses; a `decide` read of a type that asks for it carries `refusal` beside the values, for the company's
 * tool.
 */
export interface ObjectRead {
  as_of?: string | null;
  /**
   * Each time axis of the type whose value is known: a date as `YYYY-MM-DD`, an instant in UTC. The platform
   * keeps `known_at` (when the producer first knew of the object) and the time its content last changed.
   */
  axes?: Record<string, string>;
  /**
   * What the fields whose value is not known block, as the type declares it (`unobserved_blocks`): each
   * activity (`model_read`, `derive`, `claim`, or a task of the company such as `decide:close`) with the
   * fields that block it. Nothing else is blocked.
   */
  blocked?: Record<string, string[]>;
  declared_gaps?: string[];
  /** The type's derived fields, from the related objects. */
  derived?: Record<string, DerivedState>;
  derived_status?: "current" | "expired_by_input" | null;
  /** The inputs whose change expired it. */
  expired_by?: string[];
  fields?: Record<string, FieldState>;
  latches?: Record<string, string>;
  /** What its owner and participants said about it, in a context read that serves a pack. */
  memory?: ObjectMemoryOut | null;
  outcome?: OutcomeState | null;
  prohibitions?: string[];
  readings?: Record<string, ReadingResult>;
  ref: StateRef;
  refetch?: Refetch | null;
  refusal?: Refusal | null;
  state?: string | null;
  timers?: TimerState[];
  type_version?: string | null;
  values?: Record<string, ValueState>;
  /** Fields left out for this reader, and why. */
  withheld?: Record<string, "access" | "licence" | "scan">;
}

/** A shared object the subject showed interest in, as it stands now. */
export interface InterestState {
  at: string;
  /** The object as a `display` read serves it; absent once it left the working set. */
  object?: ObjectRead | null;
  /** `presented`, `engaged`, `feedback` or `watch`. */
  reason: string;
  ref: StateRef;
}

export interface TypeCoverage {
  fields: FieldCoverage[];
  /** The objects measured: the ones of the type that changed last. */
  objects: number;
  type: string;
}

/**
 * How much of each declared field the objects of each type carry, and how old it is, from the stamps
 * alone: never a value.
 */
export interface ObjectCoverage {
  types: TypeCoverage[];
}

/**
 * Where pushed values come from: only a `live` source sustains a claim, and the age of every value counts
 * from `source_observed_at`.
 */
export interface Provenance {
  scope?: "global" | "customer" | "context";
  source: "live" | "snapshot" | "cache";
  source_observed_at: string;
}

export interface ObjectPush {
  fields: Record<string, unknown>;
  /**
   * For a derived object (a customer's quote, a shared best offer): the objects its inputs are fields of, by
   * the name its type gives them, as `type:namespace:id` (`{"lead": "lead:crm:L-9"}`). When a field of one of
   * them changes, the object expires, naming the input. A shared object's inputs are shared objects: a
   * customer's object is never one.
   */
  inputs?: Record<string, string> | null;
  provenance: Provenance;
  ref: StateRef;
  /**
   * The refresh request this item answers, from the resolver worker's lease: the request is settled, and a
   * `watch_revalidation` is decided on these values even when they are not newer than the ones held.
   */
  request_id?: string | null;
  /**
   * The source's version of the object. A field moves only when this is greater than the version that last
   * wrote it; a source never reuses a version for other content.
   */
  version: number;
}

export interface ObjectPushRequest {
  objects: ObjectPush[];
}

/**
 * How many items of the request each decision took, against the hot layer, with no database statement.
 *
 * A shared object's item is `applied` when at least one of its fields moved forward: reads serve it at once,
 * and the consolidator writes it within a second with the same per-field rule, so the stored object never
 * disagrees with the answer. `stale_version`: every field was already written by this version or a greater
 * one, as a retried request finds. `out_of_set`: the object is not in the working set, and nothing is kept.
 * A subject's object is `recorded`: accepted as a system event about it, in the request's one statement,
 * and its fields move by the same rule when the event is applied.
 */
export interface ObjectPushResponse {
  applied: number;
  out_of_set: number;
  recorded?: number;
  stale_version: number;
}

/**
 * A snapshot taken in: its lines are applied as pushes of provenance `snapshot`, which never sustain a
 * claim, by the same version rule.
 */
export interface ObjectSnapshotResponse {
  import_id: string;
  /** The lines taken in. */
  objects: number;
}

/**
 * A leased request the resolver worker cannot answer: the object is not at the source, or fetching it
 * failed. The request leaves at once and its paid call counts; a `watch_revalidation` falls back to the
 * type's `unconfirmed_watch`.
 */
export interface RefreshRelease {
  outcome: "not_found" | "failed";
}

export interface RefreshReleased {
  reason: string;
  request_id: string;
}

export interface RefreshRequest {
  budget_units: number;
  lease_until: string;
  priority: "high" | "normal" | "low";
  reason: string;
  ref: StateRef;
  request_id: string;
}

export interface RefreshRequestPage {
  items: RefreshRequest[];
}

/** Where a result carries objects of a type, and which key of each item holds which field. */
export interface ResultObjects {
  fields?: Record<string, string>;
  /** The key of the item that holds the object's id. */
  id?: string;
  namespace: string;
  path?: string;
  type: string;
}

export interface ToolCapabilities {
  /** The argument that makes a call change nothing, for a counterfactual. */
  dry_run_param?: string | null;
  /** The SDK masks the fields the key may not read in the tool's output. */
  mask_output?: boolean;
  /** The tool returns more than asked: the SDK filters the residual from it. */
  overfetch?: boolean;
  /** Where the result says the tool relaxed what it was asked. */
  relax_flag?: string | null;
}

export interface ToolBinding {
  args?: BoundArg[];
  capabilities?: ToolCapabilities;
  results?: ResultObjects[];
  tool: string;
}

/**
 * How the calling source records turns, for the SDK's capture: where the values may live, and the pins
 * a turn needs to be replayable.
 */
export interface TurnRecordingSummary {
  /** `stored`, `pointer` or `hash_only`; a turn may keep less, never more. */
  content_mode: "stored" | "pointer" | "hash_only";
  /** Without one of these, a turn is kept not replayable. */
  required_pins: ("prompts" | "corpus_digest" | "model" | "assembler" | "tool_schemas")[];
}

/**
 * What the SDK keeps in its local cache: the features on, the source's tool bindings, the summarized
 * type registry, the claim contract and turn recording.
 */
export interface SdkProfile {
  claim_contract?: ClaimContractSummary | null;
  features: Feature[];
  /** How this source records turns, once the space records them. */
  recording?: TurnRecordingSummary | null;
  /** The bindings of the tools this source's agents call. */
  tool_bindings?: ToolBinding[];
  types?: (Record<string, unknown>)[];
  valid_for_s: number;
}

export interface StateReadRequest {
  fields?: string[] | null;
  purpose?: "display" | "claim" | "decide";
  readings?: string[] | null;
  refs: StateRef[];
  subject?: Handle | null;
}

export interface StateReadResponse {
  degraded?: boolean;
  objects: ObjectRead[];
}

export interface VerifyCheck {
  field: string;
  ref: StateRef;
  value?: unknown;
}

export interface StateVerifyRequest {
  checks: VerifyCheck[];
  subject?: Handle | null;
}

export interface Verdict {
  claim_safe: boolean;
  declared_gaps?: string[];
  field: string;
  matches?: boolean | null;
  prohibitions?: string[];
  ref: StateRef;
  status: "fresh" | "stale" | "expired";
}

export interface StateVerifyResponse {
  verdicts: Verdict[];
}

/**
 * The state of one subject (the `now` view): their objects of the declared types, each as a `display`
 * read serves it; the shared objects they showed interest in, and what changed since they saw them; and
 * the same as short lines for the turn block.
 */
export interface StateView {
  changes_since_seen?: ChangeSinceSeen[];
  degraded?: boolean;
  interests?: InterestState[];
  objects?: ObjectRead[];
  /**
   * The view as lines for the turn block, after `slots`: never part of the pack's `text`, so the cached
   * prefix keeps its bytes. Absent when there is nothing to say.
   */
  text?: string | null;
}

export interface StateViewRequest {
  purpose?: "display" | "claim" | "decide";
  subject: Handle;
}

/** A deriving tool's check of a declared type: the fingerprint of the schema it read now. */
export interface TypeFingerprintRequest {
  changes?: DriftChanges | null;
  fingerprint: string;
  type: string;
}

export interface TypeFingerprintResponse {
  /** Whether the fingerprint differs from the declaration's. */
  drift: boolean;
  /** The data issue of kind `drift` the check opened or counted in, when the type alerts. */
  issue_id?: string | null;
}
