// Generated by scripts/sync-spec.ts from spec/openapi/cell.json. Do not edit.
/** Turn records, replay, scenarios, the change log, data issues and the notification feed. */

import type { ObjectRef } from "./common.js";
import type { ItemError } from "./events.js";

export interface AssertionOutcome {
  detail?: string | null;
  id: string;
  kind: "tool_called" | "tool_not_called" | "hard_respected" | "no_denial_with_results" | "claims_traced" | "claims_match_state" | "no_promise_without_action" | "expected_in_topk" | "handoff_when" | "effect_once" | "budget" | "lexicon" | "tools_offered_match";
  outcome: "pass" | "fail" | "not_checked";
}

/**
 * One assertion over the run's completed executions, against its baseline. `p_value` is the one-sided
 * Fisher exact test that the run passes less often than the baseline, rounded to 6 decimals.
 */
export interface AssertionStats {
  baseline_failed: number;
  baseline_passed: number;
  /** The baseline's pass rate minus the run's. */
  drop: number;
  failed: number;
  flaky: boolean;
  id: string;
  not_checked: number;
  p_value: number;
  passed: number;
  regression: boolean;
}

/**
 * What the person is: a size, a preferred network, a diet. Said here; the lifecycle's outcomes (bought,
 * kept, returned for size) derive the rest on the server, never an agent.
 */
export interface Attribute {
  category?: string | null;
  for?: string;
  kind: "attribute";
  name: string;
  source?: "stated" | "correction";
  /** The measuring system: `BR`, `EU`, `US`. */
  system?: string | null;
  value: boolean | number | string;
}

/**
 * One entry of the change log a bisection walks: a pin that changed between two builds of an agent, in
 * the order the builds were first seen.
 */
export interface Change {
  after?: string | null;
  agent?: string | null;
  at: string;
  before?: string | null;
  kind: "prompt" | "model" | "code" | "data" | "config" | "compiler";
  /** The prompt or the tool, for those kinds. */
  name?: string | null;
}

export interface ChangePage {
  items: Change[];
  next_cursor?: string | null;
}

/** Where a claim's evidence is in the turn record: a call's field, an object's field, or a document. */
export interface ClaimEvidenceRef {
  /** The blob that keeps the quoted text. */
  anchor?: string | null;
  call_id?: string | null;
  /** The document an anchor cites. */
  document?: string | null;
  field?: string | null;
  /** An object, `type:namespace:id`. */
  ref?: string | null;
  /** The anchor's similarity. */
  score?: number | null;
}

/**
 * A number the parser read, normalized: an amount, or a range from `min` to `max`, with its unit (the
 * currency code of money, `%`, a time unit, a unit of measure or of dose), or a date, or a range of
 * dates.
 */
export interface ClaimValue {
  amount?: string | null;
  date?: string | null;
  date_from?: string | null;
  date_to?: string | null;
  max?: string | null;
  min?: string | null;
  unit?: string | null;
}

/** One claim the SDK found in an output, as the turn record carries it: kinds, spans and verdicts. */
export interface ClaimRecord {
  /**
   * What was done, which the contract's configured action decides: `rewrite_if_unequivocal` is `rewrite` when
   * the rewrite is unequivocal and `warn` otherwise, `discard_anchor_and_count` is `discard_anchor`, and a
   * claim that stands (`matched`, `quoted_found`, `anchored`) is `none`.
   */
  action: "none" | "block" | "warn" | "count" | "rewrite" | "discard_anchor";
  category: string;
  class?: "money" | "percent" | "date" | "duration" | "quantity" | "count" | "dosage" | null;
  evidence?: ClaimEvidenceRef | null;
  nature?: "computed" | "quoted" | "model" | null;
  role?: string | null;
  /** Code point offsets of the claim in the output, end exclusive. */
  span: [number, number];
  value?: ClaimValue | null;
  verdict: "matched" | "mismatch" | "stale" | "gap_not_stated" | "role_ambiguous" | "unsupported" | "no_evidence" | "quoted_found" | "quoted_missing" | "anchored" | "below_threshold" | "source_exists_claim_unverified" | "source_missing" | "not_checked" | "internal_text_found";
}

export interface DataIssue {
  acknowledged_at?: string | null;
  field?: string | null;
  issue_id: string;
  kind: "null_field" | "out_of_vocabulary" | "stale_source" | "coverage_drop" | "invalid_value" | "divergence" | "drift" | "rule_conflict";
  object_type?: string | null;
  occurrences: number;
  opened_at: string;
  refs?: ObjectRef[];
  source?: string | null;
}

export interface DataIssuePage {
  items: DataIssue[];
  next_cursor?: string | null;
}

export interface Engaged {
  /** Absent for an item of no list. */
  exposure_id?: string | null;
  for?: string;
  how: "click" | "detail" | "mention" | "add_to_cart" | "compare" | "share" | "other";
  kind: "engaged";
  ref: string;
}

export interface Feedback {
  for?: string;
  kind: "feedback";
  polarity: "positive" | "negative";
  reason_attrs?: string[];
  ref: string;
}

/** A webhook's body, for who pulls instead of receiving it: the same body, in `change_seq` order. */
export interface Notification {
  data: Record<string, unknown>;
  id: string;
  occurred_at: string;
  type: string;
}

export interface NotificationPage {
  items: Notification[];
  next_cursor?: string | null;
}

/** What the person wants or refuses, said or captured from a tool's arguments; only these become hard. */
export interface Preference {
  attr: string;
  /** Holds only in this category of the type. */
  category?: string | null;
  expires_at?: string | null;
  for?: string;
  kind: "preference";
  op: "in" | "not_in" | "eq" | "ne" | "lt" | "lte" | "gt" | "gte" | "between";
  scope?: "turn" | "session" | "persistent";
  source?: "stated" | "tool_args" | "correction";
  strength: "must" | "must_not" | "prefer" | "avoid";
  values: (boolean | number | string)[];
}

export interface PresentedItem {
  /** 1-based position in the whole list, across pages. */
  pos: number;
  ref: string;
  /**
   * The values the item showed, for the fields its type tracks or lets be claimed; what `changes_since_seen`
   * later compares against.
   */
  shown?: Record<string, boolean | number | string | null>;
  /** Which of two interleaved lists contributed the item. */
  team?: "a" | "b" | null;
}

/**
 * A list delivered to the person: the exposure. Its canonical moment is `delivered_at`, when the
 * interface bridge handed the list to the client, never when a tool returned it or the model named it.
 */
export interface Presented {
  delivered_at: string;
  exposure_id: string;
  for?: string;
  items: PresentedItem[];
  kind: "presented";
  list_id: string;
  list_kind?: string;
  /**
   * `bridge` from the interface bridge, `otel` from a `niadra.exposure` span, `tool_result` inferred from
   * what a tool returned: labeled, because it counts more than was shown.
   */
  method?: "bridge" | "otel" | "tool_result";
  offset?: number;
  /** "See more" is the same list with `page + 1`. */
  page?: number;
  parent_list_id?: string | null;
  /** How many of the first items were visible on delivery. */
  visible_k?: number | null;
}

/**
 * Moves turns from the short tier (every turn, 7 days) to the kept one, by conversation or by id, with
 * the reason: the complaint arrives days after the turn.
 */
export interface PromoteRequest {
  conversation_id?: string | null;
  reason: "complaint" | "bug_report" | "review" | "other";
  turn_ids?: string[];
}

export interface PromoteResponse {
  already_kept: number;
  /** Turns no longer in the short tier, or never recorded. */
  not_found: number;
  promoted: number;
}

/**
 * A structural check on the replayed turn's record, evaluated by the runner. The replay spec fixes each
 * kind's `args` and how it is evaluated; a kind the runner cannot evaluate yields `not_checked`.
 */
export interface ReplayAssertion {
  args?: Record<string, unknown>;
  id: string;
  kind: "tool_called" | "tool_not_called" | "hard_respected" | "no_denial_with_results" | "claims_traced" | "claims_match_state" | "no_promise_without_action" | "expected_in_topk" | "handoff_when" | "effect_once" | "budget" | "lexicon" | "tools_offered_match";
  /** Suggested by rule from the recorded turn. */
  suggested?: boolean;
  /** The one turn of the scenario it applies to; every turn when absent. */
  turn_id?: string | null;
}

/**
 * Why a turn cannot be run again: `content_mode` (`hash_only` keeps no value), `fidelity` (only a gold
 * record can be replayed), `completeness` (only a complete one) or `missing_pin` (the pin the recording
 * requires and the record lacks).
 */
export interface ReplayBlocker {
  reason: "content_mode" | "fidelity" | "completeness" | "missing_pin";
  /** E.g. `hash_only`, `bronze`, `partial` or the pin's name, `model`. */
  value: string;
}

export interface ReplayHistoryEntry {
  at: string;
  role: "customer" | "agent" | "human";
  text?: string | null;
}

export interface ReplayInput {
  kind: "message" | "action" | "event" | "timer";
  /** The customer's message that opened the turn, masked. */
  text?: string | null;
}

/** A ping of the list component: how far the person saw. */
export interface Seen {
  exposure_id: string;
  for?: string;
  kind: "seen";
  /** The highest `pos` the component showed. */
  max_index_seen: number;
}

export interface TurnAgent {
  /** The agent's name inside the source, e.g. `closing`. */
  name: string;
  /** The turn that opened this one as a sub-turn (a sub-agent, an agent as tool). */
  parent_turn_id?: string | null;
  /** Free text, e.g. `specialist` or `router`. */
  role?: string | null;
}

/**
 * A large value of the record. `sha256` is over its normalized canonical JSON (RFC 8785): the same value
 * always has the same hash.
 */
export interface TurnBlob {
  /** The value itself, only in `stored` mode. */
  content?: unknown;
  /** Where the customer keeps it, in `pointer` mode. */
  pointer?: string | null;
  sha256: string;
  /** Bytes of the canonical form. */
  size?: number | null;
}

export interface TurnCompilerPins {
  /** The context compiler's version, from the pack. */
  compiler?: string | null;
  /** The hash of the pack this turn read. */
  pack_hash?: string | null;
}

/**
 * What must be the same for a replay to reproduce this turn. The recording document says which are
 * required; a turn without one of them is kept, marked not replayable.
 */
export interface TurnPins {
  /** The version of the company's context assembler. */
  assembler?: string | null;
  /** Digest of the files the agent consults, computed in the SDK; never the files. */
  corpus_digest?: string | null;
  /** The exact model the agent called. */
  model?: string | null;
  niadra?: TurnCompilerPins | null;
  /** Prompt name -> version, e.g. `core` -> `v16`. */
  prompts?: Record<string, string>;
  /** Tool name -> hash of its schema. */
  tool_schemas?: Record<string, string>;
}

export interface TurnBuild {
  /** The framework adapter and its version, if any. */
  adapter?: string | null;
  pins?: TurnPins;
  /** E.g. `niadra-python/0.7.0`. */
  sdk?: string | null;
}

/** What the SDK measured of the constraints block on one tool call: sent, checked, violated. */
export interface TurnConstraints {
  /** The version of the constraints block applied. */
  constraints: string;
  hard_sent?: string[];
  relaxed?: "declared" | "suspected" | null;
  results_checked: number;
  unverifiable: number;
  violations: number;
}

export interface TurnProvenance {
  scope?: "global" | "customer" | "context";
  source: "live" | "snapshot" | "cache";
  source_observed_at: string;
}

/** State a tool result showed, with provenance per field; without provenance it is display only. */
export interface TurnObservation {
  fields: Record<string, unknown>;
  provenance?: TurnProvenance | null;
  /** An object as `<type>:<namespace>:<id>`, e.g. `item_variant:store:991`. */
  ref: string;
}

export interface TurnTokens {
  cached?: number;
  in: number;
  out: number;
}

/** One tool or model call of the turn, copied deep at the moment it happened. */
export interface TurnCall {
  applied?: TurnConstraints | null;
  args?: string | null;
  /** Of the normalized arguments. */
  args_hash?: string | null;
  attempt?: number;
  cache_hit?: boolean;
  call_id: string;
  cost_units?: Record<string, number>;
  effect_key?: string | null;
  kind: "tool" | "model";
  latency_ms?: number | null;
  /** The tool's name, or the model's for a model call. */
  name?: string | null;
  observations?: TurnObservation[];
  parent_call_id?: string | null;
  /** The result as the model saw it. */
  result_model?: string | null;
  /** The result as the interface got it. */
  result_ui?: string | null;
  status?: "ok" | "error" | "timeout" | "cancelled";
  synthetic?: boolean;
  tokens?: TurnTokens | null;
  /** Arguments or result arrived cut (OpenTelemetry). */
  truncated?: boolean;
}

export interface TurnCoordination {
  decision: "allow" | "defer" | "deny" | "handoff_to";
  decision_id: string;
}

export interface TurnCost {
  usd: number;
}

export interface TurnEffect {
  key: string;
  state: "reserved" | "done" | "failed" | "unknown_outcome";
}

export interface TurnOutput {
  /** A document the turn wrote, by its blob. */
  document?: string | null;
  /** The events `track()` sent for what the turn said: the text is never repeated here. */
  event_keys?: string[];
  handoff_id?: string | null;
  ui?: string | null;
}

/** A read the turn made from Niadra, by its version: the pack by ETag, a block by its version. */
export interface TurnRead {
  /** The content read, when the recording keeps it. */
  blob?: string | null;
  etag?: string | null;
  receipt_id?: string | null;
  surface: "pack" | "state" | "constraints" | "coordination" | "budget" | "history" | "agent_memory" | "agent_state";
  version?: string | null;
}

export interface Unwatch {
  for?: string;
  kind: "unwatch";
  ref: string;
}

/** An explicit "let me know when": the only way an interest raises a notice. */
export interface Watch {
  /** A `niadra-expr` expression over the object's fields. */
  condition: string;
  consent_event_key: string;
  expires_at?: string | null;
  for?: string;
  kind: "watch";
  ref: string;
}

/**
 * One turn, from its input (a message, an interface action, an event, a timer firing) to the last thing
 * it emitted to the customer or to a document.
 */
export interface TurnRecord {
  agent: TurnAgent;
  blobs?: Record<string, TurnBlob>;
  build?: TurnBuild;
  calls?: TurnCall[];
  claims?: ClaimRecord[];
  completeness?: "complete" | "partial" | "incomplete" | "unknown";
  content_mode: "stored" | "pointer" | "hash_only";
  conversation_id?: string | null;
  coordination?: TurnCoordination[];
  cost?: TurnCost | null;
  effects?: TurnEffect[];
  ended_at?: string | null;
  fidelity?: "bronze" | "silver" | "gold";
  flags?: ("error" | "guard_acted" | "guard_budget_exceeded" | "handoff" | "assertion_failed" | "synthetic" | "incomplete" | "negative_feedback" | "truncated")[];
  interactions?: (Presented | Seen | Engaged | Feedback | Preference | Attribute | Watch | Unwatch)[];
  kind?: "message" | "action" | "event" | "timer";
  latency_ms?: number | null;
  output?: TurnOutput;
  reads?: TurnRead[];
  spec?: "turn-record.v0";
  started_at: string;
  task_id?: string | null;
  turn_id: string;
}

/**
 * What the replay runner needs to run a turn again inside the company's boundary: the record, with the
 * kept values in `stored` mode and the pointers and digests otherwise; the pins; the conversation's masked
 * history up to the turn, ending with the turn's own input; and the assertions. The pack of the time is
 * the blob of the record's `pack` read.
 */
export interface ReplayCase {
  assertions?: ReplayAssertion[];
  case_id: string;
  /** When the turn leaves storage; after it, `replay_expired`. */
  expires_at: string;
  history?: ReplayHistoryEntry[];
  input: ReplayInput;
  mode: "hermetic_turn" | "hermetic_conversation" | "era_memory";
  record: TurnRecord;
  required_pins: ("prompts" | "corpus_digest" | "model" | "assembler" | "tool_schemas")[];
  scenario_id?: string | null;
  turn_id: string;
  vary?: ("prompts" | "corpus_digest" | "model" | "assembler" | "tool_schemas")[];
}

/**
 * A case for one turn, alone or as part of a scenario. `build` is the build the runner will run; every
 * pin the recording requires must match the recorded one, except the pins in `vary`, which the run changes
 * on purpose.
 */
export interface ReplayCaseRequest {
  build: TurnBuild;
  mode?: "hermetic_turn" | "hermetic_conversation" | "era_memory";
  scenario_id?: string | null;
  turn_id: string;
  vary?: ("prompts" | "corpus_digest" | "model" | "assembler" | "tool_schemas")[];
}

/**
 * One execution of one case. `infrastructure_error` (the agent raised, a blob could not be fetched or
 * did not match its digest, a timeout) is counted apart and never fails an assertion; `pin_mismatch` is a
 * case the runner stopped at its pin check.
 */
export interface ReplayResult {
  assertions?: AssertionOutcome[];
  case_id?: string | null;
  divergent_calls?: number;
  error?: string | null;
  latency_ms?: number | null;
  /** The run's input was a paraphrase of the recorded one. */
  paraphrase?: boolean;
  run: number;
  scenario_id: string;
  status: "completed" | "pin_mismatch" | "infrastructure_error";
  turn_id: string;
}

export interface Scenario {
  assertions: ReplayAssertion[];
  created_at: string;
  name: string;
  origin: "manual" | "report";
  scenario_id: string;
  status: "active" | "retired";
  turn_ids: string[];
  updated_at: string;
  /** Grows with every change of the name, the assertions or the status. */
  version: number;
}

/**
 * Turns kept as a scenario, with the assertions they must keep passing; without assertions, the ones
 * suggested by rule from the turns.
 */
export interface ScenarioCreate {
  assertions?: ReplayAssertion[];
  name: string;
  turn_ids: string[];
}

/**
 * A bug report becomes a scenario: its turns are kept and assertions suggested by rule, from the turns
 * and from words of the description. The description is read, never stored.
 */
export interface ScenarioFromReport {
  conversation_id?: string | null;
  description?: string | null;
  name?: string | null;
  turn_ids?: string[];
}

export interface ScenarioPage {
  items: Scenario[];
  next_cursor?: string | null;
}

export interface ScenarioVerdict {
  assertions: AssertionStats[];
  /** The earlier run compared against; none when it was the recording. */
  baseline_run_id?: string | null;
  completed: number;
  infrastructure_errors: number;
  /** An assertion passed and failed across the runs: its next run must include paraphrases. */
  needs_paraphrase: boolean;
  pin_mismatches: number;
  scenario_id: string;
  verdict: "pass" | "flaky" | "infrastructure_error" | "pin_mismatch" | "regression";
}

export interface ScenarioRunSummary {
  scenarios?: ScenarioVerdict[];
}

export interface ScenarioRun {
  build: TurnBuild;
  created_at: string;
  mode: "hermetic_turn" | "hermetic_conversation" | "era_memory";
  run_id: string;
  status: "pending" | "done";
  summary: ScenarioRunSummary;
  vary?: ("prompts" | "corpus_digest" | "model" | "assembler" | "tool_schemas")[];
  /** The worst of the scenarios' verdicts. */
  verdict?: "pass" | "flaky" | "infrastructure_error" | "pin_mismatch" | "regression" | null;
}

/**
 * What the company's CI reports after running the scenarios N times: the statistics stay with Niadra.
 * Every pin the recording requires must match each scenario's recorded build, except those in `vary`.
 */
export interface ScenarioRunCreate {
  build: TurnBuild;
  mode?: "hermetic_turn" | "hermetic_conversation" | "era_memory";
  results: ReplayResult[];
  runs?: number | null;
  scenario_ids: string[];
  vary?: ("prompts" | "corpus_digest" | "model" | "assembler" | "tool_schemas")[];
}

export interface ScenarioUpdate {
  assertions?: ReplayAssertion[] | null;
  name?: string | null;
  status?: "active" | "retired" | null;
}

/** A search over the kept tier. The conversation id travels in the body, never in the URL. */
export interface TurnSearchRequest {
  agent?: string | null;
  conversation_id?: string | null;
  cursor?: string | null;
  flags?: ("error" | "guard_acted" | "guard_budget_exceeded" | "handoff" | "assertion_failed" | "synthetic" | "incomplete" | "negative_feedback" | "truncated")[];
  limit?: number;
  since?: string | null;
  until?: string | null;
}

export interface TurnSummary {
  agent: string;
  completeness: "complete" | "partial" | "incomplete" | "unknown";
  fidelity: "bronze" | "silver" | "gold";
  flags?: ("error" | "guard_acted" | "guard_budget_exceeded" | "handoff" | "assertion_failed" | "synthetic" | "incomplete" | "negative_feedback" | "truncated")[];
  kind: "message" | "action" | "event" | "timer";
  replayable: boolean;
  started_at: string;
  tier: "short" | "kept";
  turn_id: string;
}

export interface TurnSearchResponse {
  items: TurnSummary[];
  next_cursor?: string | null;
}

/** A recorded turn as the viewer shows it. In `pointer` and `hash_only` modes, blobs have no content. */
export interface TurnView {
  kept_until?: string | null;
  record: TurnRecord;
  /** Why the turn cannot be run again; empty when it can. */
  replay_blockers?: ReplayBlocker[];
  /** Every pin the recording requires is there. */
  replayable: boolean;
  tier: "short" | "kept";
}

export interface TurnsRequest {
  turns: TurnRecord[];
}

/** 200 when every turn was taken, 207 with one error per rejected turn (by index). */
export interface TurnsResponse {
  accepted: number;
  /** Turns already recorded: the same turn sent twice is one. */
  duplicates: number;
  errors?: ItemError[];
}
