// Generated by scripts/sync-spec.ts from spec/openapi/cell.json. Do not edit.
/** Turn records, replay, scenarios, the change log, data issues and the notification feed. */

import type { ObjectRef } from "./common.js";
import type { ItemError } from "./events.js";

/** One entry of the change log the bisection walks. */
export interface Change {
  after?: string | null;
  agent?: string | null;
  at: string;
  before?: string | null;
  kind: "prompt" | "model" | "code" | "data" | "config" | "compiler";
}

export interface ChangePage {
  items: Change[];
  next_cursor?: string | null;
}

export interface DataIssue {
  acknowledged_at?: string | null;
  field?: string | null;
  issue_id: string;
  kind: "null_field" | "out_of_vocabulary" | "stale_source" | "coverage_drop" | "invalid_value" | "divergence" | "drift" | "rule_conflict";
  object_type?: string | null;
  occurrences: number;
  opened_at: string;
  refs?: ObjectRef[];
  source?: string | null;
}

export interface DataIssuePage {
  items: DataIssue[];
  next_cursor?: string | null;
}

/** A webhook's body, for who pulls instead of receiving it: the same body, in `change_seq` order. */
export interface Notification {
  data: Record<string, unknown>;
  id: string;
  occurred_at: string;
  type: string;
}

export interface NotificationPage {
  items: Notification[];
  next_cursor?: string | null;
}

/**
 * Moves turns from the short tier (every turn, 7 days) to the kept one, by conversation or by id, with
 * the reason: the complaint arrives days after the turn.
 */
export interface PromoteRequest {
  conversation_id?: string | null;
  reason: "complaint" | "bug_report" | "review" | "other";
  turn_ids?: string[];
}

export interface PromoteResponse {
  already_kept: number;
  /** Turns no longer in the short tier, or never recorded. */
  not_found: number;
  promoted: number;
}

export interface TurnAgent {
  /** The agent's name inside the source, e.g. `closing`. */
  name: string;
  /** The turn that opened this one as a sub-turn (a sub-agent, an agent as tool). */
  parent_turn_id?: string | null;
  /** Free text, e.g. `specialist` or `router`. */
  role?: string | null;
}

/**
 * A large value of the record. `sha256` is over its normalized canonical JSON (RFC 8785): the same value
 * always has the same hash.
 */
export interface TurnBlob {
  /** The value itself, only in `stored` mode. */
  content?: unknown;
  /** Where the customer keeps it, in `pointer` mode. */
  pointer?: string | null;
  sha256: string;
  /** Bytes of the canonical form. */
  size?: number | null;
}

export interface TurnCompilerPins {
  /** The context compiler's version, from the pack. */
  compiler?: string | null;
  /** The hash of the pack this turn read. */
  pack_hash?: string | null;
}

/**
 * What must be the same for a replay to reproduce this turn. The recording document says which are
 * required; a turn without one of them is kept, marked not replayable.
 */
export interface TurnPins {
  /** The version of the company's context assembler. */
  assembler?: string | null;
  /** Digest of the files the agent consults, computed in the SDK; never the files. */
  corpus_digest?: string | null;
  /** The exact model the agent called. */
  model?: string | null;
  niadra?: TurnCompilerPins | null;
  /** Prompt name -> version, e.g. `core` -> `v16`. */
  prompts?: Record<string, string>;
  /** Tool name -> hash of its schema. */
  tool_schemas?: Record<string, string>;
}

export interface TurnBuild {
  /** The framework adapter and its version, if any. */
  adapter?: string | null;
  pins?: TurnPins;
  /** E.g. `niadra-python/0.7.0`. */
  sdk?: string | null;
}

/** What the SDK measured of the constraints block on one tool call: sent, checked, violated. */
export interface TurnConstraints {
  /** The version of the constraints block applied. */
  constraints: string;
  hard_sent?: string[];
  relaxed?: "declared" | "suspected" | null;
  results_checked: number;
  unverifiable: number;
  violations: number;
}

export interface TurnProvenance {
  scope?: "global" | "customer" | "context";
  source: "live" | "snapshot" | "cache";
  source_observed_at: string;
}

/** State a tool result showed, with provenance per field; without provenance it is display only. */
export interface TurnObservation {
  fields: Record<string, unknown>;
  provenance?: TurnProvenance | null;
  /** An object as `<type>:<namespace>:<id>`, e.g. `item_variant:store:991`. */
  ref: string;
}

export interface TurnTokens {
  cached?: number;
  in: number;
  out: number;
}

/** One tool or model call of the turn, copied deep at the moment it happened. */
export interface TurnCall {
  applied?: TurnConstraints | null;
  args?: string | null;
  /** Of the normalized arguments. */
  args_hash?: string | null;
  attempt?: number;
  cache_hit?: boolean;
  call_id: string;
  cost_units?: Record<string, number>;
  effect_key?: string | null;
  kind: "tool" | "model";
  latency_ms?: number | null;
  /** The tool's name, or the model's for a model call. */
  name?: string | null;
  observations?: TurnObservation[];
  parent_call_id?: string | null;
  /** The result as the model saw it. */
  result_model?: string | null;
  /** The result as the interface got it. */
  result_ui?: string | null;
  status?: "ok" | "error" | "timeout" | "cancelled";
  synthetic?: boolean;
  tokens?: TurnTokens | null;
  /** Arguments or result arrived cut (OpenTelemetry). */
  truncated?: boolean;
}

export interface TurnEvidence {
  /** The quoted text a fact is anchored to. */
  anchor?: string | null;
  call_id?: string | null;
  field?: string | null;
}

/**
 * A claim contract verdict, found by the SDK before the text reached the customer or a document. The
 * fields are the claim contract's record; its spec fixes the vocabularies of `verdict` and
 * `action`, so this record takes them as names until that model replaces this one.
 */
export interface TurnClaim {
  /** E.g. `none`, `warn`, `count`, `block`. */
  action?: string;
  category: string;
  class?: "money" | "percent" | "date" | "quantity" | "count" | "duration" | "dosage" | "text" | null;
  evidence?: TurnEvidence | null;
  nature?: "computed" | "quoted" | "model" | null;
  role?: string | null;
  /** Start and end offsets in the output. */
  span?: [number, number] | null;
  value?: unknown;
  /** E.g. `matched`, `role_ambiguous`, `below_threshold`. */
  verdict: string;
}

export interface TurnCoordination {
  decision: "allow" | "defer" | "deny" | "handoff_to";
  decision_id: string;
}

export interface TurnCost {
  usd: number;
}

export interface TurnEffect {
  key: string;
  state: "reserved" | "done" | "failed" | "unknown_outcome";
}

/**
 * What the person was shown or did in the turn. Its fields are the `interaction.v0` spec's,
 * validated when the turn is applied; until that spec's `Interaction` model lands, the record fixes only
 * the kind and keeps the rest as it came. The swap narrows the type and changes no document.
 */
export interface TurnInteraction {
  kind: "presented" | "seen" | "engaged" | "feedback" | "preference" | "attribute" | "watch" | "unwatch";
  [key: string]: unknown;
}

export interface TurnOutput {
  /** A document the turn wrote, by its blob. */
  document?: string | null;
  /** The events `track()` sent for what the turn said: the text is never repeated here. */
  event_keys?: string[];
  handoff_id?: string | null;
  ui?: string | null;
}

/** A read the turn made from Niadra, by its version: the pack by ETag, a block by its version. */
export interface TurnRead {
  /** The content read, when the recording keeps it. */
  blob?: string | null;
  etag?: string | null;
  receipt_id?: string | null;
  surface: "pack" | "state" | "constraints" | "coordination" | "budget" | "history" | "agent_memory" | "agent_state";
  version?: string | null;
}

/**
 * One turn, from its input (a message, an interface action, an event, a timer firing) to the last thing
 * it emitted to the customer or to a document.
 */
export interface TurnRecord {
  agent: TurnAgent;
  blobs?: Record<string, TurnBlob>;
  build?: TurnBuild;
  calls?: TurnCall[];
  claims?: TurnClaim[];
  completeness?: "complete" | "partial" | "incomplete" | "unknown";
  content_mode: "stored" | "pointer" | "hash_only";
  conversation_id?: string | null;
  coordination?: TurnCoordination[];
  cost?: TurnCost | null;
  effects?: TurnEffect[];
  ended_at?: string | null;
  fidelity?: "bronze" | "silver" | "gold";
  flags?: ("error" | "guard_acted" | "guard_budget_exceeded" | "handoff" | "assertion_failed" | "synthetic" | "incomplete" | "negative_feedback" | "truncated")[];
  interactions?: TurnInteraction[];
  kind?: "message" | "action" | "event" | "timer";
  latency_ms?: number | null;
  output?: TurnOutput;
  reads?: TurnRead[];
  spec?: "turn-record.v0";
  started_at: string;
  task_id?: string | null;
  turn_id: string;
}

/**
 * What the SDK's replay runner needs to run the turn again inside the customer's boundary: the frame,
 * pointers and hashes, pins, the pack and view of the time, the masked history up to the turn and the
 * suggested assertions. A pin that does not match stops the case with `pin_mismatch`.
 */
export interface ReplayCase {
  assertions?: (Record<string, unknown>)[];
  case_id: string;
  /** After it, the case answers 410 `replay_expired`. */
  expires_at: string;
  history?: (Record<string, unknown>)[];
  mode: "hermetic_turn" | "hermetic_conversation" | "era_memory";
  record: TurnRecord;
}

export interface ReplayCaseRequest {
  mode?: "hermetic_turn" | "hermetic_conversation" | "era_memory";
  turn_id: string;
}

export interface Scenario {
  assertions: (Record<string, unknown>)[];
  created_at: string;
  name: string;
  origin: "manual" | "report";
  scenario_id: string;
  status: "active" | "retired";
  turn_ids: string[];
  version: number;
}

export interface ScenarioCreate {
  assertions?: (Record<string, unknown>)[];
  name: string;
  turn_ids: string[];
}

/** A bug report becomes a scenario: its turns are promoted and assertions suggested by rule. */
export interface ScenarioFromReport {
  conversation_id?: string | null;
  description?: string | null;
  turn_ids?: string[];
}

export interface ScenarioPage {
  items: Scenario[];
  next_cursor?: string | null;
}

export interface ScenarioRun {
  run_id: string;
  status: "pending" | "done";
  summary?: Record<string, unknown>;
  verdict?: "pass" | "regression" | "flaky" | "infrastructure_error" | null;
}

/** The customer's CI reports N executions of the scenarios; the statistics stay with Niadra. */
export interface ScenarioRunCreate {
  build: TurnBuild;
  results: (Record<string, unknown>)[];
  scenario_ids: string[];
}

export interface ScenarioUpdate {
  assertions?: (Record<string, unknown>)[] | null;
  name?: string | null;
  status?: "active" | "retired" | null;
}

/** A search over the kept tier. The conversation id travels in the body, never in the URL. */
export interface TurnSearchRequest {
  agent?: string | null;
  conversation_id?: string | null;
  cursor?: string | null;
  flags?: ("error" | "guard_acted" | "guard_budget_exceeded" | "handoff" | "assertion_failed" | "synthetic" | "incomplete" | "negative_feedback" | "truncated")[];
  limit?: number;
  since?: string | null;
  until?: string | null;
}

export interface TurnSummary {
  agent: string;
  completeness: "complete" | "partial" | "incomplete" | "unknown";
  fidelity: "bronze" | "silver" | "gold";
  flags?: ("error" | "guard_acted" | "guard_budget_exceeded" | "handoff" | "assertion_failed" | "synthetic" | "incomplete" | "negative_feedback" | "truncated")[];
  kind: "message" | "action" | "event" | "timer";
  replayable: boolean;
  started_at: string;
  tier: "short" | "kept";
  turn_id: string;
}

export interface TurnSearchResponse {
  items: TurnSummary[];
  next_cursor?: string | null;
}

/** A recorded turn as the viewer shows it. In `pointer` and `hash_only` modes, blobs have no content. */
export interface TurnView {
  kept_until?: string | null;
  record: TurnRecord;
  /** Every pin the recording requires is there. */
  replayable: boolean;
  tier: "short" | "kept";
}

export interface TurnsRequest {
  turns: TurnRecord[];
}

/** 200 when every turn was taken, 207 with one error per rejected turn (by index). */
export interface TurnsResponse {
  accepted: number;
  /** Turns already recorded: the same turn sent twice is one. */
  duplicates: number;
  errors?: ItemError[];
}
