/**
 * Keeps the SDK's copies of the Niadra specifications current, and writes the code generated from them.
 *
 *     pnpm sync-spec
 *     pnpm sync-spec --server ../niadra-back --spec ../niadra-spec
 *
 * `--server` cuts the routes tagged in `TAGS` out of the server's OpenAPI document (`openapi/cell.json`)
 * into `spec/openapi/cell.json`, with every schema they reach and its text as a public SDK may carry it.
 * `--spec` copies the Context Pack schema the SDK reads (`schemas/context-pack.v1.json`), the conformance
 * vectors (`vectors/*.json`) and the Context Pack, claim contract and turn record examples. Every run then
 * writes the types of those routes (`src/types/<module>.ts`) and their methods (`src/api.ts`) from `spec/openapi/cell.json`. `test/generated.test.ts` fails when a generated file differs
 * from what this script writes, so regenerating is this one command. It runs on Node 22.6 or later, which
 * strips the types itself.
 */
import { copyFileSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const CUT = join(ROOT, "spec", "openapi", "cell.json");
const HEADER = "// Generated by scripts/sync-spec.ts from spec/openapi/cell.json. Do not edit.\n";

/**
 * The server's route tags this SDK generates, and the module their types go to. A schema lands in the
 * module of the first tag, in this order, whose routes reach it.
 */
const TAGS: Record<string, string> = {
  turns: "turns",
  notifications: "turns",
  state: "state",
  signals: "signals",
  coordination: "coordination",
};
const MODULE_DOCS: Record<string, string> = {
  turns: "Turn records, replay, scenarios, the change log, data issues and the notification feed.",
  state:
    "Typed state: objects a system of record pushes, reads with a purpose, the agent's working state and the SDK profile.",
  signals:
    "Subject signals, the constraints block, the reviewable profile, review requests, legal holds and measurement.",
  coordination:
    "Ownership and effects: the coordination decision, declarations, claims and locks, effects exactly once, handoffs, suppressions and the contact token's public keys.",
};
const API_DOC = [
  "Every route of the turn record, typed state, subject signals and coordination, one method each, named as the",
  "server names the operation, in camelCase: `niadra.api`.",
  "",
  "Unlike the rest of the SDK, these methods never fail open: they reject with the API's error. The calls built",
  "on them decide what fails open and what fails closed, per purpose. A route of a feature the space did not",
  "turn on answers 404, as a route that does not exist.",
].join("\n");
/** Schemas the SDK already mirrors by hand, and where they live. */
const EXISTING: Record<string, string> = {
  Handle: "./common.js",
  ObjectRef: "./common.js",
  Problem: "./common.js",
  ItemError: "./events.js",
  HandleType: "./vocabulary.js",
  SubjectKind: "./vocabulary.js",
  Verification: "./vocabulary.js",
};
/** Words that name how the server was planned and built, never what it does: a public SDK carries none. */
const INTERNAL =
  /\bfronts? A\d\b|\(A\d\)|\b(?:core|the) wave\b|\bphase \d\b|\bintegrator\b|\bstudy \d+\b|\bestudo\b/i;
const SUCCESS = ["200", "201", "202", "204", "207"];

export interface Schema {
  $ref?: string;
  type?: string;
  format?: string;
  description?: string;
  enum?: unknown[];
  const?: unknown;
  anyOf?: Schema[];
  items?: Schema;
  prefixItems?: Schema[];
  properties?: Record<string, Schema>;
  required?: string[];
  additionalProperties?: Schema | boolean;
  patternProperties?: Record<string, Schema>;
  default?: unknown;
  title?: string;
  oneOf?: Schema[];
  discriminator?: { propertyName: string; mapping?: Record<string, string> };
}

interface Parameter {
  name: string;
  in: string;
  required?: boolean;
  schema: Schema;
}

interface Operation {
  operationId: string;
  tags?: string[];
  description?: string;
  parameters?: Parameter[];
  requestBody?: { content?: Record<string, { schema?: Schema }> };
  responses: Record<string, { content?: Record<string, { schema?: Schema }> }>;
}

export interface Document {
  openapi: string;
  info: unknown;
  paths: Record<string, Record<string, Operation>>;
  components: { schemas: Record<string, Schema> };
}

interface Route {
  name: string;
  tag: string;
  method: string;
  path: string;
  body: string | null;
  response: string | null;
  /** A success answer may come without a body, which resolves `null`. */
  optional: boolean;
  pathParams: string[];
  query: Parameter[];
  idempotent: boolean;
  description: string | null;
}

const refName = (ref: string): string => ref.slice(ref.lastIndexOf("/") + 1);
const camel = (name: string): string => name.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());

function* refs(node: unknown): Generator<string> {
  if (Array.isArray(node)) {
    for (const value of node) yield* refs(value);
  } else if (typeof node === "object" && node !== null) {
    const ref = (node as { $ref?: unknown }).$ref;
    if (typeof ref === "string") yield refName(ref);
    for (const value of Object.values(node)) yield* refs(value);
  }
}

function reach(roots: unknown, schemas: Record<string, Schema>): Set<string> {
  const seen = new Set<string>();
  const pending = [...refs(roots)];
  for (let name = pending.pop(); name !== undefined; name = pending.pop()) {
    if (seen.has(name)) continue;
    seen.add(name);
    pending.push(...refs(schemas[name]));
  }
  return seen;
}

/** The server's text, which a public SDK carries as it is: one naming internal planning stops the run. */
export function publicText(text: string | undefined, where: string): string | null {
  if (!text) return null;
  const found = INTERNAL.exec(text);
  if (found) {
    throw new Error(`the description of ${where} names internal planning (${JSON.stringify(found[0])}); fix it on the server`);
  }
  return text.trim();
}

function published(node: unknown, where: string): unknown {
  if (Array.isArray(node)) return node.map((value) => published(value, where));
  if (typeof node !== "object" || node === null) return node;
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(node)) {
    if (key === "description" && typeof value === "string") {
      const text = publicText(value, where);
      if (text) out[key] = text;
    } else {
      out[key] = published(value, `${where}/${key}`);
    }
  }
  return out;
}

function sortedKeys(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(sortedKeys);
  if (typeof node !== "object" || node === null) return node;
  const entries = Object.entries(node).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return Object.fromEntries(entries.map(([key, value]) => [key, sortedKeys(value)]));
}

/** The operations tagged in `TAGS` and the schemas they reach, as an OpenAPI document of its own. */
export function cut(document: Document): Document {
  const paths: Document["paths"] = {};
  for (const [path, methods] of Object.entries(document.paths)) {
    const kept = Object.entries(methods)
      .filter(([, op]) => (op.tags ?? []).some((tag) => tag in TAGS))
      .map(([method, op]) => [method, structuredClone(op)] as const);
    if (kept.length > 0) paths[path] = Object.fromEntries(kept);
  }
  const schemas = { ...document.components.schemas };
  for (const methods of Object.values(paths)) for (const op of Object.values(methods)) hoistBody(op, schemas);
  const names = [...reach(paths, schemas)].sort();
  const renames = splitNames(names);
  const result = {
    openapi: document.openapi,
    info: document.info,
    paths,
    components: { schemas: Object.fromEntries(names.map((name) => [renames.get(name) ?? name, schemas[name]])) },
  };
  return sortedKeys(published(renamed(result, renames), "")) as Document;
}

/**
 * Names for the halves of a model the server documents twice, as it validates it and as it serializes it
 * (`Name-Input`, `Name-Output`): the model's own name for one of them, and `NameOutput` when both are reached.
 */
export function splitNames(names: readonly string[]): Map<string, string> {
  const present = new Set(names);
  const out = new Map<string, string>();
  for (const name of names) {
    const match = /^(.+)-(Input|Output)$/.exec(name);
    if (!match) continue;
    const [, base = "", half] = match;
    const both = present.has(`${base}-Input`) && present.has(`${base}-Output`);
    const target = both && half === "Output" ? `${base}Output` : base;
    if (present.has(target)) throw new Error(`${name}: the name ${target} is taken`);
    out.set(name, target);
  }
  return out;
}

function renamed(node: unknown, renames: ReadonlyMap<string, string>): unknown {
  if (Array.isArray(node)) return node.map((value) => renamed(value, renames));
  if (typeof node !== "object" || node === null) return node;
  const out = Object.fromEntries(Object.entries(node).map(([key, value]) => [key, renamed(value, renames)]));
  const ref = out.$ref;
  if (typeof ref === "string") {
    const target = renames.get(refName(ref));
    if (target !== undefined) out.$ref = `#/components/schemas/${target}`;
  }
  return out;
}

/** A body the server declares inline (a route that parses its own body) as the named schema it is. */
function hoistBody(op: Operation, schemas: Record<string, Schema>): void {
  const content = op.requestBody?.content?.["application/json"];
  if (!content?.schema || content.schema.$ref) return;
  const { $id: _id, ...schema } = content.schema as Schema & { $id?: string };
  const name = schema.title;
  const known = name === undefined ? undefined : schemas[name];
  if (!name || (known && JSON.stringify(sortedKeys(known)) !== JSON.stringify(sortedKeys(schema)))) {
    throw new Error(`${op.operationId}: an inline body with no title of its own`);
  }
  schemas[name] = schema;
  content.schema = { $ref: `#/components/schemas/${name}` };
}

function routes(document: Document): Route[] {
  const found: Route[] = [];
  const order = Object.keys(TAGS);
  for (const [path, methods] of Object.entries(document.paths)) {
    for (const [method, op] of Object.entries(methods)) {
      const suffix = `${path.replace(/\W/g, "_")}_${method}`;
      if (!op.operationId.endsWith(suffix)) throw new Error(`${op.operationId}: not named the way FastAPI names operations`);
      const params = op.parameters ?? [];
      const body = op.requestBody?.content?.["application/json"]?.schema?.$ref;
      const answers = SUCCESS.filter((s) => s in op.responses).map((s) => op.responses[s]?.content?.["application/json"]?.schema?.$ref);
      if (new Set(answers.filter((a) => a !== undefined)).size > 1) throw new Error(`${op.operationId}: success answers of different shapes`);
      const answer = answers.find((a) => a !== undefined);
      const tag = (op.tags ?? []).find((t) => t in TAGS);
      if (tag === undefined) throw new Error(`${op.operationId}: no tag this SDK generates`);
      found.push({
        name: op.operationId.slice(0, -suffix.length),
        tag,
        method: method.toUpperCase(),
        path,
        body: body ? refName(body) : null,
        response: answer ? refName(answer) : null,
        optional: answer !== undefined && answers.includes(undefined),
        pathParams: params.filter((p) => p.in === "path").map((p) => p.name),
        query: params.filter((p) => p.in === "query"),
        idempotent: params.some((p) => p.in === "header" && p.name === "Idempotency-Key"),
        description: publicText(op.description, op.operationId),
      });
    }
  }
  const rank = (route: Route): string => `${order.indexOf(route.tag)} ${route.path} ${route.method}`;
  return found.sort((a, b) => (rank(a) < rank(b) ? -1 : rank(a) > rank(b) ? 1 : 0));
}

/** Every schema after the ones it refers to, the same order the Python SDK writes. */
function ordered(schemas: Record<string, Schema>): string[] {
  const done: string[] = [];
  const visit = (name: string, path: string[]): void => {
    if (done.includes(name) || path.includes(name)) return;
    for (const ref of [...new Set(refs(schemas[name]))].sort()) visit(ref, [...path, name]);
    done.push(name);
  };
  for (const name of Object.keys(schemas).sort()) visit(name, []);
  return done;
}

/** Breaks a line longer than `width` at its spaces. */
function wrap(line: string, width: number): string[] {
  const lines: string[] = [];
  let current = "";
  for (const word of line.split(" ")) {
    if (current && current.length + 1 + word.length > width) {
      lines.push(current);
      current = word;
    } else {
      current = current ? `${current} ${word}` : word;
    }
  }
  return [...lines, current];
}

function comment(text: string, indent: string): string {
  const lines = text.split("\n").flatMap((line) => (line ? wrap(line, 110 - indent.length - 3) : [""]));
  if (lines.length === 1) return `${indent}/** ${text} */\n`;
  return `${indent}/**\n${lines.map((line) => (line ? `${indent} * ${line}` : `${indent} *`)).join("\n")}\n${indent} */\n`;
}

function unwrap(schema: Schema): [Schema, boolean] {
  const options = schema.anyOf;
  if (options?.length === 2) {
    const inner = options.filter((o) => o.type !== "null" || Object.keys(o).length !== 1);
    if (inner.length === 1 && inner[0]) return [inner[0], true];
  }
  return [schema, false];
}

class TypeWriter {
  readonly imports = new Map<string, Set<string>>();
  // Plain fields: Node strips types but runs no TypeScript-only syntax such as parameter properties.
  private readonly moduleOf: Map<string, string>;
  private readonly here: string;

  constructor(moduleOf: Map<string, string>, here: string) {
    this.moduleOf = moduleOf;
    this.here = here;
  }

  ref(name: string): string {
    const module = this.moduleOf.get(name);
    if (module === undefined) throw new Error(`${name}: no module`);
    if (module !== this.here) {
      const names = this.imports.get(module) ?? new Set<string>();
      names.add(name);
      this.imports.set(module, names);
    }
    return name;
  }

  type(schema: Schema): string {
    if (schema.$ref) return this.ref(refName(schema.$ref));
    if (schema.anyOf) {
      const [inner, nullable] = unwrap(schema);
      if (nullable) return `${this.type(inner)} | null`;
      // `integer` and `number` are both `number`: each constituent once.
      return [...new Set(schema.anyOf.map((option) => this.type(option)))].join(" | ");
    }
    // A discriminated union is a union: each member's own literal `kind` tells them apart.
    if (schema.oneOf) return schema.oneOf.map((option) => this.type(option)).join(" | ");
    if (schema.const !== undefined) return JSON.stringify(schema.const);
    if (schema.enum) return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
    switch (schema.type) {
      case "string":
        return "string";
      case "integer":
      case "number":
        return "number";
      case "boolean":
        return "boolean";
      case "null":
        return "null";
      case "array": {
        if (schema.prefixItems) return `[${schema.prefixItems.map((item) => this.type(item)).join(", ")}]`;
        const item = this.type(schema.items ?? {});
        return /[ |]/.test(item) ? `(${item})[]` : `${item}[]`;
      }
      case "object": {
        if (schema.properties && Object.keys(schema.properties).length > 0) break;
        const value = schema.patternProperties ? Object.values(schema.patternProperties)[0] : schema.additionalProperties;
        return `Record<string, ${value === undefined || typeof value === "boolean" ? "unknown" : this.type(value)}>`;
      }
      case undefined:
        return "unknown";
    }
    throw new Error(`no TypeScript type for ${JSON.stringify(schema).slice(0, 200)}`);
  }

  definition(name: string, schema: Schema): string {
    const doc = publicText(schema.description, name);
    const head = doc ? comment(doc, "") : "";
    if (schema.type !== "object") return `${head}export type ${name} = ${this.type(schema)};\n`;
    const required = new Set(schema.required ?? []);
    let body = "";
    for (const [wire, property] of Object.entries(schema.properties ?? {})) {
      const text = publicText(property.description, `${name}.${wire}`);
      const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(wire) ? wire : JSON.stringify(wire);
      body += (text ? comment(text, "  ") : "") + `  ${key}${required.has(wire) ? "" : "?"}: ${this.type(property)};\n`;
    }
    if (schema.additionalProperties === true) body += "  [key: string]: unknown;\n";
    return `${head}export interface ${name} {\n${body}}\n`;
  }

  importLines(): string {
    return [...this.imports.entries()]
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
      .map(([module, names]) => `import type { ${[...names].sort().join(", ")} } from "${module}";\n`)
      .join("");
  }
}

function paramsType(route: Route): string | null {
  const fields = route.query.map((p) => {
    const [inner] = unwrap(p.schema);
    const type = inner.type === "integer" || inner.type === "number" ? "number" : inner.type === "boolean" ? "boolean" : "string";
    return p.required ? `${p.name}: ${type}` : `${p.name}?: ${type}${p.schema.default === undefined ? " | null" : ""}`;
  });
  if (route.idempotent) fields.push("idempotency_key?: string");
  return fields.length > 0 ? `{ ${fields.join("; ")} }` : null;
}

function method(route: Route, types: Map<string, Set<string>>, moduleOf: Map<string, string>): string {
  const use = (name: string): string => {
    const module = moduleOf.get(name);
    if (module === undefined) throw new Error(`${name}: no module`);
    const names = types.get(module) ?? new Set<string>();
    names.add(name);
    types.set(module, names);
    return name;
  };
  const args: string[] = route.pathParams.map((name) => `${camel(name)}: string`);
  let path = route.path;
  for (const name of route.pathParams) path = path.replace(`{${name}}`, `\${segment(${camel(name)})}`);
  if (route.body) args.push(`body: ${use(route.body)}`);
  const params = paramsType(route);
  const required = route.query.some((p) => p.required);
  if (params) args.push(required ? `params: ${params}` : `params: ${params} = {}`);
  args.push("options: RequestOptions = {}");
  const fields = [`method: "${route.method}"`, path.includes("${") ? `path: \`${path}\`` : `path: "${path}"`];
  if (route.body) fields.push("body");
  if (route.query.length > 0) {
    const values = route.query.map((p) =>
      p.schema.default === undefined || p.required ? `${p.name}: params.${p.name}` : `${p.name}: params.${p.name} ?? ${JSON.stringify(p.schema.default)}`,
    );
    fields.push(`query: { ${values.join(", ")} }`);
  }
  if (route.idempotent) fields.push("idempotencyKey: params.idempotency_key ?? uuidv7()");
  const returns = route.response ? `${use(route.response)}${route.optional ? " | null" : ""}` : "void";
  const doc = `\`${route.method} ${route.path}\`.${route.description ? ` ${route.description}` : ""}`;
  return (
    comment(doc, "  ") +
    `  ${camel(route.name)}(${args.join(", ")}): Promise<${returns}> {\n` +
    `    return this.call({ ${fields.join(", ")} }, options);\n` +
    "  }\n"
  );
}

/** Every generated file, by its path in the repository. */
export function generate(document: Document): Map<string, string> {
  const schemas = document.components.schemas;
  // Two server models named alike are written with their module path; a public SDK never carries one.
  const unnamed = Object.keys(schemas).filter((name) => name.includes("__"));
  if (unnamed.length > 0) throw new Error(`schemas named by the server's module path: ${unnamed.join(", ")}`);
  const all = routes(document);
  const moduleOf = new Map<string, string>(Object.entries(EXISTING));
  for (const [tag, module] of Object.entries(TAGS)) {
    const roots = all.filter((r) => r.tag === tag).flatMap((r) => [r.body, r.response].filter((n) => n !== null).map((n) => ({ $ref: n })));
    for (const name of [...reach(roots, schemas)].sort()) if (!moduleOf.has(name)) moduleOf.set(name, `./${module}.js`);
  }
  const files = new Map<string, string>();
  for (const module of new Set(Object.values(TAGS))) {
    const here = `./${module}.js`;
    const writer = new TypeWriter(moduleOf, here);
    const names = ordered(schemas).filter((name) => moduleOf.get(name) === here);
    const definitions = names.map((name) => writer.definition(name, schemas[name] ?? {})).join("\n");
    const doc = MODULE_DOCS[module] ?? "";
    const imports = writer.importLines();
    files.set(`src/types/${module}.ts`, `${HEADER}${comment(doc, "")}${imports ? `\n${imports}` : ""}\n${definitions}`);
  }
  const types = new Map<string, Set<string>>();
  const sources = new Map<string, string>([...moduleOf.entries()].map(([name, module]) => [name, `./types/${module.slice(2)}`]));
  const methods = all.map((route) => method(route, types, sources)).join("\n");
  const typeImports = [...types.entries()]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([module, names]) => `import type { ${[...names].sort().join(", ")} } from "${module}";\n`)
    .join("");
  files.set(
    "src/api.ts",
    `${HEADER}${comment(API_DOC, "")}\nimport type { RequestOptions } from "./context.js";\nimport { uuidv7 } from "./ids.js";\n` +
      `import { segment } from "./routes.js";\nimport type { RouteCall } from "./routes.js";\n${typeImports}\n` +
      `${comment("The routes of `niadra.api`. See the module.", "")}export class Api {\n` +
      "  constructor(private readonly call: RouteCall) {}\n\n" +
      `${methods}}\n`,
  );
  return files;
}

function copySpec(spec: string): void {
  copyFileSync(join(spec, "schemas", "context-pack.v1.json"), join(ROOT, "spec", "context-pack.v1.json"));
  console.log("copied schemas/context-pack.v1.json");
  for (const folder of ["vectors", "examples/context-pack", "examples/claim-contract", "examples/turn-record"]) {
    let entries: string[];
    try {
      entries = readdirSync(join(spec, folder)).filter((name) => name.endsWith(".json")).sort();
    } catch {
      continue;
    }
    mkdirSync(join(ROOT, "spec", folder), { recursive: true });
    for (const name of entries) {
      copyFileSync(join(spec, folder, name), join(ROOT, "spec", folder, name));
      console.log(`copied ${folder}/${name}`);
    }
  }
}

function main(argv: string[]): void {
  const option = (name: string): string | undefined => {
    const at = argv.indexOf(name);
    return at === -1 ? undefined : argv[at + 1];
  };
  const server = option("--server");
  const spec = option("--spec");
  if (server) {
    const document = JSON.parse(readFileSync(join(server, "openapi", "cell.json"), "utf8")) as Document;
    mkdirSync(dirname(CUT), { recursive: true });
    writeFileSync(CUT, `${JSON.stringify(cut(document), null, 2)}\n`);
  }
  if (spec) copySpec(spec);
  for (const [path, text] of generate(JSON.parse(readFileSync(CUT, "utf8")) as Document)) {
    writeFileSync(join(ROOT, path), text);
    console.log(`wrote ${path}`);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main(process.argv.slice(2));
