// Generated by scripts/sync-spec.ts from spec/openapi/cell.json. Do not edit.
/**
 * Every route of the turn record, typed state, subject signals and coordination, one method each, named as
 * the
 * server names the operation, in camelCase: `niadra.api`.
 *
 * Unlike the rest of the SDK, these methods never fail open: they reject with the API's error, and with
 * `NiadraNotAvailableError` (501) while the server has not built the route. The calls built on them decide
 * what fails open and what fails closed, per purpose. A route of a feature the space did not turn on answers
 * 404, as a route that does not exist.
 */

import type { RequestOptions } from "./context.js";
import { uuidv7 } from "./ids.js";
import { segment } from "./routes.js";
import type { RouteCall } from "./routes.js";
import type { CheckBatchRequest, CheckBatchResponse, CheckRequest, CheckResult, ClaimRelease, ClaimRequest, ContactKeys, CoordinationReportPage, DeclareRequest, DeclareResult, Effect, EffectReserve, EffectSettle, Handoff, HandoffCreate, HandoffOutcome, OwnershipClaim, ShadowRequest, ShadowRun, SuppressionPage, SuppressionSalt } from "./types/coordination.js";
import type { AttributionReport, ConstraintsBlock, ConstraintsRequest, CounterfactualRun, CounterfactualRunCreate, Inference, InferenceCorrection, InferencePage, InterleavingReport, LegalHold, LegalHoldCreate, LegalHoldRelease, OutcomePage, PowerRequest, PowerResult, ReconcileRequest, ReconcileResult, ReviewRequest, ReviewRequestCreate, ReviewRequestPage, ReviewResolution, UnmetDemandPage } from "./types/signals.js";
import type { AgentState, AgentStateReadRequest, AgentStateWrite, AgentStateWriteResult, ContentRelease, ContentReleaseResult, ObjectCoverage, ObjectPushRequest, ObjectPushResponse, ObjectSnapshotResponse, RefreshRequestPage, SdkProfile, StateReadRequest, StateReadResponse, StateVerifyRequest, StateVerifyResponse, StateView, StateViewRequest, TypeFingerprintRequest, TypeFingerprintResponse } from "./types/state.js";
import type { ChangePage, DataIssue, DataIssuePage, NotificationPage, PromoteRequest, PromoteResponse, ReplayCase, ReplayCaseRequest, Scenario, ScenarioCreate, ScenarioFromReport, ScenarioPage, ScenarioRun, ScenarioRunCreate, ScenarioUpdate, TurnSearchRequest, TurnSearchResponse, TurnView, TurnsRequest, TurnsResponse } from "./types/turns.js";

/** The routes of `niadra.api`. See the module. */
export class Api {
  constructor(private readonly call: RouteCall) {}

  /** `GET /v1/changes`. */
  changes(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<ChangePage> {
    return this.call({ method: "GET", path: "/v1/changes", query: { cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /** `GET /v1/data-issues`. */
  dataIssues(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<DataIssuePage> {
    return this.call({ method: "GET", path: "/v1/data-issues", query: { cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /** `POST /v1/data-issues/{issue_id}/ack`. */
  acknowledgeDataIssue(issueId: string, options: RequestOptions = {}): Promise<DataIssue> {
    return this.call({ method: "POST", path: `/v1/data-issues/${segment(issueId)}/ack` }, options);
  }

  /** `POST /v1/replay/cases`. */
  replayCase(body: ReplayCaseRequest, options: RequestOptions = {}): Promise<ReplayCase> {
    return this.call({ method: "POST", path: "/v1/replay/cases", body }, options);
  }

  /** `POST /v1/scenario-runs`. */
  createScenarioRun(body: ScenarioRunCreate, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<ScenarioRun> {
    return this.call({ method: "POST", path: "/v1/scenario-runs", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `GET /v1/scenario-runs/{run_id}`. */
  readScenarioRun(runId: string, options: RequestOptions = {}): Promise<ScenarioRun> {
    return this.call({ method: "GET", path: `/v1/scenario-runs/${segment(runId)}` }, options);
  }

  /** `GET /v1/scenarios`. */
  listScenarios(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<ScenarioPage> {
    return this.call({ method: "GET", path: "/v1/scenarios", query: { cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /** `POST /v1/scenarios`. */
  createScenario(body: ScenarioCreate, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Scenario> {
    return this.call({ method: "POST", path: "/v1/scenarios", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/scenarios/from-report`. */
  scenarioFromReport(body: ScenarioFromReport, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Scenario> {
    return this.call({ method: "POST", path: "/v1/scenarios/from-report", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `PATCH /v1/scenarios/{scenario_id}`. */
  updateScenario(scenarioId: string, body: ScenarioUpdate, options: RequestOptions = {}): Promise<Scenario> {
    return this.call({ method: "PATCH", path: `/v1/scenarios/${segment(scenarioId)}`, body }, options);
  }

  /**
   * `POST /v1/turns`. Up to 50 turn records, the body in zstd, gzip or plain JSON. The same turn sent twice
   * is one turn.
   */
  recordTurns(body: TurnsRequest, options: RequestOptions = {}): Promise<TurnsResponse> {
    return this.call({ method: "POST", path: "/v1/turns", body }, options);
  }

  /**
   * `POST /v1/turns/promote`. Promoting is idempotent by itself: a turn promoted again counts as
   * `already_kept`.
   */
  promoteTurns(body: PromoteRequest, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<PromoteResponse> {
    return this.call({ method: "POST", path: "/v1/turns/promote", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/turns/search`. The kept tier, newest first, by conversation, agent, time and flags. */
  searchTurns(body: TurnSearchRequest, options: RequestOptions = {}): Promise<TurnSearchResponse> {
    return this.call({ method: "POST", path: "/v1/turns/search", body }, options);
  }

  /** `GET /v1/turns/{turn_id}`. One turn from either tier, by its id: 404 once its tier let it go. */
  readTurn(turnId: string, options: RequestOptions = {}): Promise<TurnView> {
    return this.call({ method: "GET", path: `/v1/turns/${segment(turnId)}` }, options);
  }

  /** `GET /v1/notifications`. */
  notifications(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<NotificationPage> {
    return this.call({ method: "GET", path: "/v1/notifications", query: { cursor: params.cursor, limit: params.limit ?? 100 } }, options);
  }

  /**
   * `PUT /v1/agent-state`. A write by the agent's code: over the cap it answers `stored: false`, never an
   * error.
   */
  writeAgentState(body: AgentStateWrite, options: RequestOptions = {}): Promise<AgentStateWriteResult> {
    return this.call({ method: "PUT", path: "/v1/agent-state", body }, options);
  }

  /**
   * `POST /v1/agent-state/read`. The working state of one scope and agent: version 0 and an empty body when
   * it was never written.
   */
  readAgentState(body: AgentStateReadRequest, options: RequestOptions = {}): Promise<AgentState> {
    return this.call({ method: "POST", path: "/v1/agent-state/read", body }, options);
  }

  /** `POST /v1/content/{ref}/release`. */
  releaseContent(ref: string, body: ContentRelease, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<ContentReleaseResult> {
    return this.call({ method: "POST", path: `/v1/content/${segment(ref)}/release`, body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `GET /v1/objects/coverage`. */
  objectCoverage(options: RequestOptions = {}): Promise<ObjectCoverage> {
    return this.call({ method: "GET", path: "/v1/objects/coverage" }, options);
  }

  /**
   * `POST /v1/objects/push`. State from a system of record: a shared object's items are decided against the
   * working set's hot
   * copy with no database statement and written within a second; a customer's, kept in one statement.
   */
  pushObjects(body: ObjectPushRequest, options: RequestOptions = {}): Promise<ObjectPushResponse> {
    return this.call({ method: "POST", path: "/v1/objects/push", body }, options);
  }

  /**
   * `POST /v1/objects/snapshot`. Reconciliation of a shared type from its system of record: NDJSON, one push
   * item per line, applied as
   * pushes of provenance `snapshot` by the same version rule.
   */
  snapshotObjects(params: { type: string }, options: RequestOptions = {}): Promise<ObjectSnapshotResponse> {
    return this.call({ method: "POST", path: "/v1/objects/snapshot", query: { type: params.type } }, options);
  }

  /**
   * `GET /v1/sdk/profile`. What the SDK keeps in its local cache, from the configuration alone: no database,
   * no receipt.
   */
  sdkProfile(options: RequestOptions = {}): Promise<SdkProfile> {
    return this.call({ method: "GET", path: "/v1/sdk/profile" }, options);
  }

  /**
   * `POST /v1/state/read`. Objects by reference, each for the read's purpose: values with their logical
   * value, stamps, source and
   * freshness computed now, what may not be claimed, and the refusal a `decide` read of a type asks for.
   */
  stateRead(body: StateReadRequest, options: RequestOptions = {}): Promise<StateReadResponse> {
    return this.call({ method: "POST", path: "/v1/state/read", body }, options);
  }

  /** `GET /v1/state/refresh-requests`. */
  refreshRequests(params: { limit?: number } = {}, options: RequestOptions = {}): Promise<RefreshRequestPage> {
    return this.call({ method: "GET", path: "/v1/state/refresh-requests", query: { limit: params.limit ?? 50 } }, options);
  }

  /** `POST /v1/state/verify`. */
  stateVerify(body: StateVerifyRequest, options: RequestOptions = {}): Promise<StateVerifyResponse> {
    return this.call({ method: "POST", path: "/v1/state/verify", body }, options);
  }

  /** `POST /v1/state/view`. */
  stateView(body: StateViewRequest, options: RequestOptions = {}): Promise<StateView> {
    return this.call({ method: "POST", path: "/v1/state/view", body }, options);
  }

  /** `POST /v1/types/fingerprint`. */
  typeFingerprint(body: TypeFingerprintRequest, options: RequestOptions = {}): Promise<TypeFingerprintResponse> {
    return this.call({ method: "POST", path: "/v1/types/fingerprint", body }, options);
  }

  /**
   * `POST /v1/constraints`. The constraints block of one subject, the one `include: ["constraints"]` adds to
   * a context read;
   * `for` asks for a beneficiary's.
   */
  constraints(body: ConstraintsRequest, options: RequestOptions = {}): Promise<ConstraintsBlock> {
    return this.call({ method: "POST", path: "/v1/constraints", body }, options);
  }

  /**
   * `POST /v1/legal-holds`. Keeps a handle's, an object's or a conversation's data from purging until the
   * release.
   */
  createLegalHold(body: LegalHoldCreate, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<LegalHold> {
    return this.call({ method: "POST", path: "/v1/legal-holds", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /**
   * `POST /v1/legal-holds/{hold_id}/release`. What erasures left waiting under the hold goes once it is
   * released.
   */
  releaseLegalHold(holdId: string, body: LegalHoldRelease, options: RequestOptions = {}): Promise<LegalHold> {
    return this.call({ method: "POST", path: `/v1/legal-holds/${segment(holdId)}/release`, body }, options);
  }

  /**
   * `GET /v1/measure/attribution`. Outcomes and value by day, agent, method and band, without a person:
   * deterministic and probable
   * apart.
   */
  attribution(params: { since: string; until: string }, options: RequestOptions = {}): Promise<AttributionReport> {
    return this.call({ method: "GET", path: "/v1/measure/attribution", query: { since: params.since, until: params.until } }, options);
  }

  /** `POST /v1/measure/counterfactual-runs`. */
  counterfactualRun(body: CounterfactualRunCreate, options: RequestOptions = {}): Promise<CounterfactualRun> {
    return this.call({ method: "POST", path: "/v1/measure/counterfactual-runs", body }, options);
  }

  /** `GET /v1/measure/interleaving`. */
  interleaving(options: RequestOptions = {}): Promise<InterleavingReport> {
    return this.call({ method: "GET", path: "/v1/measure/interleaving" }, options);
  }

  /**
   * `GET /v1/measure/outcomes`. Outcomes attributed to what agents did, newest first: each link with its
   * method, band and finality.
   */
  outcomes(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<OutcomePage> {
    return this.call({ method: "GET", path: "/v1/measure/outcomes", query: { cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /** `POST /v1/measure/power`. */
  power(body: PowerRequest, options: RequestOptions = {}): Promise<PowerResult> {
    return this.call({ method: "POST", path: "/v1/measure/power", body }, options);
  }

  /**
   * `POST /v1/measure/reconcile`. The period's attributed lines against the company's BI file, line by line,
   * with the deviation kept.
   */
  reconcile(body: ReconcileRequest, options: RequestOptions = {}): Promise<ReconcileResult> {
    return this.call({ method: "POST", path: "/v1/measure/reconcile", body }, options);
  }

  /** `GET /v1/measure/unmet-demand`. */
  unmetDemand(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<UnmetDemandPage> {
    return this.call({ method: "GET", path: "/v1/measure/unmet-demand", query: { cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /**
   * `GET /v1/profiles/{profile_id}/inferences`. Every inference about the subject, with its origin, evidence,
   * confidence, use and date.
   */
  listInferences(profileId: string, params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<InferencePage> {
    return this.call({ method: "GET", path: `/v1/profiles/${segment(profileId)}/inferences`, query: { cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /**
   * `DELETE /v1/profiles/{profile_id}/inferences/{key}`. A tombstone: the same evidence never infers it
   * again.
   */
  deleteInference(profileId: string, key: string, options: RequestOptions = {}): Promise<void> {
    return this.call({ method: "DELETE", path: `/v1/profiles/${segment(profileId)}/inferences/${segment(key)}` }, options);
  }

  /**
   * `POST /v1/profiles/{profile_id}/inferences/{key}/correct`. The subject's value becomes a stated
   * preference or attribute; the inference is deleted.
   */
  correctInference(profileId: string, key: string, body: InferenceCorrection, options: RequestOptions = {}): Promise<Inference> {
    return this.call({ method: "POST", path: `/v1/profiles/${segment(profileId)}/inferences/${segment(key)}/correct`, body }, options);
  }

  /**
   * `POST /v1/profiles/{profile_id}/review-requests`. Sent to the controller's data protection officer with
   * the explanation built from receipts.
   */
  createReviewRequest(profileId: string, body: ReviewRequestCreate, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<ReviewRequest> {
    return this.call({ method: "POST", path: `/v1/profiles/${segment(profileId)}/review-requests`, body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `GET /v1/review-requests`. */
  listReviewRequests(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<ReviewRequestPage> {
    return this.call({ method: "GET", path: "/v1/review-requests", query: { cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /** `POST /v1/review-requests/{request_id}/resolve`. The controller's decision, recorded once. */
  resolveReviewRequest(requestId: string, body: ReviewResolution, options: RequestOptions = {}): Promise<ReviewRequest> {
    return this.call({ method: "POST", path: `/v1/review-requests/${segment(requestId)}/resolve`, body }, options);
  }

  /** `GET /.well-known/niadra-contact-keys.json`. */
  contactKeys(params: { space: string }, options: RequestOptions = {}): Promise<ContactKeys> {
    return this.call({ method: "GET", path: "/.well-known/niadra-contact-keys.json", query: { space: params.space } }, options);
  }

  /** `POST /v1/coordination/check`. */
  check(body: CheckRequest, options: RequestOptions = {}): Promise<CheckResult> {
    return this.call({ method: "POST", path: "/v1/coordination/check", body }, options);
  }

  /** `POST /v1/coordination/check/batch`. */
  checkBatch(body: CheckBatchRequest, options: RequestOptions = {}): Promise<CheckBatchResponse> {
    return this.call({ method: "POST", path: "/v1/coordination/check/batch", body }, options);
  }

  /** `POST /v1/coordination/claims`. */
  claim(body: ClaimRequest, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<OwnershipClaim> {
    return this.call({ method: "POST", path: "/v1/coordination/claims", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/coordination/claims/{claim_id}/release`. */
  releaseClaim(claimId: string, body: ClaimRelease, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<OwnershipClaim> {
    return this.call({ method: "POST", path: `/v1/coordination/claims/${segment(claimId)}/release`, body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/coordination/declare`. */
  declare(body: DeclareRequest, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<DeclareResult> {
    return this.call({ method: "POST", path: "/v1/coordination/declare", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/coordination/effects`. */
  reserveEffect(body: EffectReserve, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Effect | null> {
    return this.call({ method: "POST", path: "/v1/coordination/effects", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/coordination/effects/{effect_id}/settle`. */
  settleEffect(effectId: string, body: EffectSettle, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Effect> {
    return this.call({ method: "POST", path: `/v1/coordination/effects/${segment(effectId)}/settle`, body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `GET /v1/coordination/reports`. */
  reports(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<CoordinationReportPage> {
    return this.call({ method: "GET", path: "/v1/coordination/reports", query: { cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /** `POST /v1/coordination/shadow`. */
  shadow(body: ShadowRequest, options: RequestOptions = {}): Promise<ShadowRun> {
    return this.call({ method: "POST", path: "/v1/coordination/shadow", body }, options);
  }

  /** `POST /v1/handoffs`. */
  createHandoff(body: HandoffCreate, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Handoff> {
    return this.call({ method: "POST", path: "/v1/handoffs", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `GET /v1/handoffs/{handoff_id}`. */
  readHandoff(handoffId: string, options: RequestOptions = {}): Promise<Handoff> {
    return this.call({ method: "GET", path: `/v1/handoffs/${segment(handoffId)}` }, options);
  }

  /** `POST /v1/handoffs/{handoff_id}/accept`. */
  acceptHandoff(handoffId: string, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Handoff> {
    return this.call({ method: "POST", path: `/v1/handoffs/${segment(handoffId)}/accept`, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/handoffs/{handoff_id}/outcome`. */
  handoffOutcome(handoffId: string, body: HandoffOutcome, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Handoff> {
    return this.call({ method: "POST", path: `/v1/handoffs/${segment(handoffId)}/outcome`, body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `GET /v1/suppressions`. */
  suppressions(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<SuppressionPage> {
    return this.call({ method: "GET", path: "/v1/suppressions", query: { cursor: params.cursor, limit: params.limit ?? 200 } }, options);
  }

  /** `GET /v1/suppressions/salt`. */
  suppressionSalt(options: RequestOptions = {}): Promise<SuppressionSalt> {
    return this.call({ method: "GET", path: "/v1/suppressions/salt" }, options);
  }
}
