// Generated by scripts/sync-spec.ts from spec/openapi/cell.json. Do not edit.
/**
 * Every route of the turn record, typed state, subject signals and coordination, one method each, named as
 * the
 * server names the operation, in camelCase: `niadra.api`.
 *
 * Unlike the rest of the SDK, these methods never fail open: they reject with the API's error, and with
 * `NiadraNotAvailableError` (501) while the server has not built the route. The calls built on them decide
 * what fails open and what fails closed, per purpose. A route of a feature the space did not turn on answers
 * 404, as a route that does not exist.
 */

import type { RequestOptions } from "./context.js";
import { uuidv7 } from "./ids.js";
import { segment } from "./routes.js";
import type { RouteCall } from "./routes.js";
import type { CheckBatchRequest, CheckBatchResponse, CheckRequest, CheckResult, ClaimRelease, ClaimRequest, ContactKeys, CoordinationOverview, CoordinationReportPage, DeclareRequest, DeclareResult, Effect, EffectReserve, EffectSettle, Handoff, HandoffCreate, HandoffOutcome, OwnershipClaim, ShadowRequest, ShadowRun, SuppressionPage, SuppressionSalt } from "./types/coordination.js";
import type { AttributionReport, BiUpload, BiUploadRequest, ConstraintsBlock, ConstraintsRequest, CounterfactualRun, CounterfactualRunCreate, CounterfactualRunPage, ExperimentReport, Inference, InferenceCorrection, InferencePage, InterleavingReport, LegalHold, LegalHoldCreate, LegalHoldRelease, OutcomePage, PowerRequest, PowerResult, ReconcileRequest, ReconcileResult, ReviewRequest, ReviewRequestCreate, ReviewRequestPage, ReviewResolution, UnmetDemandPage } from "./types/signals.js";
import type { AgentState, AgentStateMetaPage, AgentStateReadRequest, AgentStateWrite, AgentStateWriteResult, ContentRelease, ContentReleaseResult, ObjectCoverage, ObjectPushRequest, ObjectPushResponse, ObjectSnapshotResponse, RefreshRequestPage, SdkProfile, StateReadRequest, StateReadResponse, StateVerifyRequest, StateVerifyResponse, StateView, StateViewRequest, TypeFingerprintRequest, TypeFingerprintResponse } from "./types/state.js";
import type { ChangePage, DataIssue, DataIssuePage, NotificationPage, PromoteRequest, PromoteResponse, ReplayCase, ReplayCaseRequest, Scenario, ScenarioCreate, ScenarioFromReport, ScenarioPage, ScenarioRun, ScenarioRunCreate, ScenarioUpdate, TurnIndexPage, TurnSearchRequest, TurnSearchResponse, TurnView, TurnsRequest, TurnsResponse } from "./types/turns.js";

/** The routes of `niadra.api`. See the module. */
export class Api {
  constructor(private readonly call: RouteCall) {}

  /** `GET /v1/changes`. What changed between consecutive builds of each agent, newest first. */
  changes(params: { agent?: string | null; cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<ChangePage> {
    return this.call({ method: "GET", path: "/v1/changes", query: { agent: params.agent, cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /**
   * `GET /v1/data-issues`. Newest opened first: data problems, drift, divergence and rule conflicts, with no
   * personal data.
   */
  dataIssues(params: { status?: string; kind?: string | null; cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<DataIssuePage> {
    return this.call({ method: "GET", path: "/v1/data-issues", query: { status: params.status ?? "open", kind: params.kind, cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /**
   * `POST /v1/data-issues/{issue_id}/ack`. Closes the issue; the next occurrence of the same problem opens a
   * new one.
   */
  acknowledgeDataIssue(issueId: string, options: RequestOptions = {}): Promise<DataIssue> {
    return this.call({ method: "POST", path: `/v1/data-issues/${segment(issueId)}/ack` }, options);
  }

  /**
   * `POST /v1/replay/cases`. One turn with what a runner needs to run it again, once the running build shares
   * its pins.
   */
  replayCase(body: ReplayCaseRequest, options: RequestOptions = {}): Promise<ReplayCase> {
    return this.call({ method: "POST", path: "/v1/replay/cases", body }, options);
  }

  /**
   * `POST /v1/scenario-runs`. The executions the company's CI ran; the answer carries the verdict already
   * decided.
   */
  createScenarioRun(body: ScenarioRunCreate, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<ScenarioRun> {
    return this.call({ method: "POST", path: "/v1/scenario-runs", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `GET /v1/scenario-runs/{run_id}`. */
  readScenarioRun(runId: string, options: RequestOptions = {}): Promise<ScenarioRun> {
    return this.call({ method: "GET", path: `/v1/scenario-runs/${segment(runId)}` }, options);
  }

  /**
   * `GET /v1/scenarios`. A status's scenarios, newest first; or the ones named by `ids`, whatever their
   * status.
   */
  listScenarios(params: { ids?: string | null; status?: string; cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<ScenarioPage> {
    return this.call({ method: "GET", path: "/v1/scenarios", query: { ids: params.ids, status: params.status ?? "active", cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /** `POST /v1/scenarios`. Keeps the turns as a scenario; without assertions, the ones suggested by rule. */
  createScenario(body: ScenarioCreate, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Scenario> {
    return this.call({ method: "POST", path: "/v1/scenarios", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/scenarios/from-report`. */
  scenarioFromReport(body: ScenarioFromReport, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Scenario> {
    return this.call({ method: "POST", path: "/v1/scenarios/from-report", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `GET /v1/scenarios/{scenario_id}`. */
  readScenario(scenarioId: string, options: RequestOptions = {}): Promise<Scenario> {
    return this.call({ method: "GET", path: `/v1/scenarios/${segment(scenarioId)}` }, options);
  }

  /** `PATCH /v1/scenarios/{scenario_id}`. */
  updateScenario(scenarioId: string, body: ScenarioUpdate, options: RequestOptions = {}): Promise<Scenario> {
    return this.call({ method: "PATCH", path: `/v1/scenarios/${segment(scenarioId)}`, body }, options);
  }

  /**
   * `POST /v1/turns`. Up to 50 turn records, the body in zstd, gzip or plain JSON. The same turn sent twice
   * is one turn.
   */
  recordTurns(body: TurnsRequest, options: RequestOptions = {}): Promise<TurnsResponse> {
    return this.call({ method: "POST", path: "/v1/turns", body }, options);
  }

  /**
   * `GET /v1/turns/index/{day}`. The rows the kept tier took on a UTC day with their digests, which make the
   * `turns.root` of the day's
   * `audit.root` event: the company anchors them in its own audit chain.
   */
  turnIndex(day: string, params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<TurnIndexPage> {
    return this.call({ method: "GET", path: `/v1/turns/index/${segment(day)}`, query: { cursor: params.cursor, limit: params.limit ?? 500 } }, options);
  }

  /**
   * `POST /v1/turns/promote`. Promoting is idempotent by itself: a turn promoted again counts as
   * `already_kept`.
   */
  promoteTurns(body: PromoteRequest, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<PromoteResponse> {
    return this.call({ method: "POST", path: "/v1/turns/promote", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/turns/search`. The kept tier, newest first, by conversation, agent, time and flags. */
  searchTurns(body: TurnSearchRequest, options: RequestOptions = {}): Promise<TurnSearchResponse> {
    return this.call({ method: "POST", path: "/v1/turns/search", body }, options);
  }

  /** `GET /v1/turns/{turn_id}`. One turn from either tier, by its id: 404 once its tier let it go. */
  readTurn(turnId: string, options: RequestOptions = {}): Promise<TurnView> {
    return this.call({ method: "GET", path: `/v1/turns/${segment(turnId)}` }, options);
  }

  /**
   * `GET /v1/notifications`. The events the webhooks carry, oldest first, from `cursor` (the start of the
   * feed without one); a
   * poll with nothing new answers the same cursor. Events stay 7 days.
   */
  notifications(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<NotificationPage> {
    return this.call({ method: "GET", path: "/v1/notifications", query: { cursor: params.cursor, limit: params.limit ?? 100 } }, options);
  }

  /**
   * `PUT /v1/agent-state`. A write by the agent's code: over the cap it answers `stored: false`, never an
   * error.
   */
  writeAgentState(body: AgentStateWrite, options: RequestOptions = {}): Promise<AgentStateWriteResult> {
    return this.call({ method: "PUT", path: "/v1/agent-state", body }, options);
  }

  /**
   * `POST /v1/agent-state/read`. The working state of one scope and agent: version 0 and an empty body when
   * it was never written.
   */
  readAgentState(body: AgentStateReadRequest, options: RequestOptions = {}): Promise<AgentState> {
    return this.call({ method: "POST", path: "/v1/agent-state/read", body }, options);
  }

  /**
   * `POST /v1/content/{ref}/release`. A person clears content the scan flagged or holds, with a reason and a
   * receipt; the object's reads
   * serve it from then on.
   */
  releaseContent(ref: string, body: ContentRelease, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<ContentReleaseResult> {
    return this.call({ method: "POST", path: `/v1/content/${segment(ref)}/release`, body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /**
   * `GET /v1/objects/coverage`. Each declared type's fields, the share of its objects that carry each and how
   * old it is: the Console's
   * Types screen. Stamps only, never a value.
   */
  objectCoverage(options: RequestOptions = {}): Promise<ObjectCoverage> {
    return this.call({ method: "GET", path: "/v1/objects/coverage" }, options);
  }

  /**
   * `POST /v1/objects/push`. State from a system of record: a shared object's items are decided against the
   * working set's hot
   * copy with no database statement and written within a second; a customer's, kept in one statement.
   */
  pushObjects(body: ObjectPushRequest, options: RequestOptions = {}): Promise<ObjectPushResponse> {
    return this.call({ method: "POST", path: "/v1/objects/push", body }, options);
  }

  /**
   * `POST /v1/objects/snapshot`. Reconciliation of a shared type from its system of record: NDJSON, one push
   * item per line, applied as
   * pushes of provenance `snapshot` by the same version rule.
   */
  snapshotObjects(params: { type: string }, options: RequestOptions = {}): Promise<ObjectSnapshotResponse> {
    return this.call({ method: "POST", path: "/v1/objects/snapshot", query: { type: params.type } }, options);
  }

  /**
   * `GET /v1/profiles/{profile_id}/agent-state`. The customer's working states, as the Console shows them:
   * size, version and dates, never the
   * content.
   */
  profileAgentStates(profileId: string, options: RequestOptions = {}): Promise<AgentStateMetaPage> {
    return this.call({ method: "GET", path: `/v1/profiles/${segment(profileId)}/agent-state` }, options);
  }

  /**
   * `GET /v1/sdk/profile`. What the SDK keeps in its local cache, from the configuration alone: no database,
   * no receipt.
   */
  sdkProfile(options: RequestOptions = {}): Promise<SdkProfile> {
    return this.call({ method: "GET", path: "/v1/sdk/profile" }, options);
  }

  /**
   * `POST /v1/state/read`. Objects by reference, each for the read's purpose: values with their logical
   * value, stamps, source and
   * freshness computed now, what may not be claimed, and the refusal a `decide` read of a type asks for.
   */
  stateRead(body: StateReadRequest, options: RequestOptions = {}): Promise<StateReadResponse> {
    return this.call({ method: "POST", path: "/v1/state/read", body }, options);
  }

  /**
   * `GET /v1/state/refresh-requests`. The company's resolver worker takes what to fetch again: the higher
   * priorities and the older first,
   * each leased to it for 60 seconds; a request it does not answer is offered again, three times at most.
   */
  refreshRequests(params: { limit?: number } = {}, options: RequestOptions = {}): Promise<RefreshRequestPage> {
    return this.call({ method: "GET", path: "/v1/state/refresh-requests", query: { limit: params.limit ?? 50 } }, options);
  }

  /**
   * `POST /v1/state/verify`. A verdict per object and field for a claim, without waiting for the source:
   * whether it may be claimed
   * now, whether a value given matches the one held, and what may not be said with data this old.
   */
  stateVerify(body: StateVerifyRequest, options: RequestOptions = {}): Promise<StateVerifyResponse> {
    return this.call({ method: "POST", path: "/v1/state/verify", body }, options);
  }

  /**
   * `POST /v1/state/view`. The subject's `now` view for the read's purpose: their objects, the shared objects
   * they showed
   * interest in and what changed since they saw them, and the same as lines for the turn block.
   */
  stateView(body: StateViewRequest, options: RequestOptions = {}): Promise<StateView> {
    return this.call({ method: "POST", path: "/v1/state/view", body }, options);
  }

  /**
   * `POST /v1/types/fingerprint`. A deriving tool's check of a declared type: a fingerprint other than the
   * declaration's is drift, and a
   * type that alerts opens a data issue of kind `drift`, or counts the open one, and announces `type.drift`.
   * Only the fingerprint and the counts of what changed travel: never a name, a value or a definition.
   */
  typeFingerprint(body: TypeFingerprintRequest, options: RequestOptions = {}): Promise<TypeFingerprintResponse> {
    return this.call({ method: "POST", path: "/v1/types/fingerprint", body }, options);
  }

  /**
   * `POST /v1/constraints`. The constraints block of one subject, the one `include: ["constraints"]` adds to
   * a context read;
   * `for` asks for a beneficiary's. With `tool`, it comes rendered through the tool's binding for this
   * source, in advisory mode; 422 when the space binds no such tool for it.
   */
  constraints(body: ConstraintsRequest, options: RequestOptions = {}): Promise<ConstraintsBlock> {
    return this.call({ method: "POST", path: "/v1/constraints", body }, options);
  }

  /**
   * `POST /v1/legal-holds`. Keeps a handle's, an object's or a conversation's data from purging until the
   * release.
   */
  createLegalHold(body: LegalHoldCreate, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<LegalHold> {
    return this.call({ method: "POST", path: "/v1/legal-holds", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /**
   * `POST /v1/legal-holds/{hold_id}/release`. What erasures left waiting under the hold goes once it is
   * released.
   */
  releaseLegalHold(holdId: string, body: LegalHoldRelease, options: RequestOptions = {}): Promise<LegalHold> {
    return this.call({ method: "POST", path: `/v1/legal-holds/${segment(holdId)}/release`, body }, options);
  }

  /**
   * `GET /v1/measure/attribution`. Outcomes and value by day, agent, method and band, without a person:
   * deterministic and probable
   * apart.
   */
  attribution(params: { since: string; until: string }, options: RequestOptions = {}): Promise<AttributionReport> {
    return this.call({ method: "GET", path: "/v1/measure/attribution", query: { since: params.since, until: params.until } }, options);
  }

  /** `GET /v1/measure/counterfactual-runs`. */
  counterfactualRuns(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<CounterfactualRunPage> {
    return this.call({ method: "GET", path: "/v1/measure/counterfactual-runs", query: { cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /**
   * `POST /v1/measure/counterfactual-runs`. What a runner in the company's CI measured: whether an element
   * changes what a tool returns, against the
   * tool's own noise. Positions and overlaps only (the tool counterfactual spec).
   */
  counterfactualRun(body: CounterfactualRunCreate, options: RequestOptions = {}): Promise<CounterfactualRun> {
    return this.call({ method: "POST", path: "/v1/measure/counterfactual-runs", body }, options);
  }

  /** `GET /v1/measure/counterfactual-runs/{run_id}`. */
  counterfactualRunRead(runId: string, options: RequestOptions = {}): Promise<CounterfactualRun> {
    return this.call({ method: "GET", path: `/v1/measure/counterfactual-runs/${segment(runId)}` }, options);
  }

  /**
   * `GET /v1/measure/experiments`. Each experiment on an element or an agent, arm by arm against `control`:
   * CUPED-adjusted, with the
   * mixture sequential test, whose p-value and interval hold however often the report is read.
   */
  experiments(options: RequestOptions = {}): Promise<ExperimentReport> {
    return this.call({ method: "GET", path: "/v1/measure/experiments" }, options);
  }

  /**
   * `GET /v1/measure/interleaving`. Interleaved lists of a tool's two rankings: which one engagement
   * credited, with the sign test.
   */
  interleaving(params: { since: string; until: string }, options: RequestOptions = {}): Promise<InterleavingReport> {
    return this.call({ method: "GET", path: "/v1/measure/interleaving", query: { since: params.since, until: params.until } }, options);
  }

  /**
   * `GET /v1/measure/outcomes`. Outcomes attributed to what agents did, newest first: each link with its
   * method, band and finality.
   */
  outcomes(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<OutcomePage> {
    return this.call({ method: "GET", path: "/v1/measure/outcomes", query: { cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /**
   * `POST /v1/measure/power`. How many days of the space's traffic a relative difference needs, looked at
   * once or every day.
   */
  power(body: PowerRequest, options: RequestOptions = {}): Promise<PowerResult> {
    return this.call({ method: "POST", path: "/v1/measure/power", body }, options);
  }

  /**
   * `POST /v1/measure/reconcile`. The period's attributed lines against the company's BI file, line by line,
   * with the deviation kept.
   */
  reconcile(body: ReconcileRequest, options: RequestOptions = {}): Promise<ReconcileResult> {
    return this.call({ method: "POST", path: "/v1/measure/reconcile", body }, options);
  }

  /**
   * `POST /v1/measure/reconcile/uploads`. Where to upload the company's BI file for a reconciliation: a
   * short-lived link for those bytes only.
   */
  reconcileUpload(body: BiUploadRequest, options: RequestOptions = {}): Promise<BiUpload> {
    return this.call({ method: "POST", path: "/v1/measure/reconcile/uploads", body }, options);
  }

  /**
   * `GET /v1/measure/unmet-demand`. What people asked the tools for and did not get, by week and combination
   * of what was asked, where at
   * least the space's minimum of distinct people asked it: never per person.
   */
  unmetDemand(params: { since: string; until: string; tool?: string | null; cursor?: string | null; limit?: number }, options: RequestOptions = {}): Promise<UnmetDemandPage> {
    return this.call({ method: "GET", path: "/v1/measure/unmet-demand", query: { since: params.since, until: params.until, tool: params.tool, cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /**
   * `GET /v1/profiles/{profile_id}/inferences`. Every inference about the subject, with its origin, evidence,
   * confidence, use and date.
   */
  listInferences(profileId: string, params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<InferencePage> {
    return this.call({ method: "GET", path: `/v1/profiles/${segment(profileId)}/inferences`, query: { cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /**
   * `DELETE /v1/profiles/{profile_id}/inferences/{key}`. A tombstone: the same evidence never infers it
   * again.
   */
  deleteInference(profileId: string, key: string, options: RequestOptions = {}): Promise<void> {
    return this.call({ method: "DELETE", path: `/v1/profiles/${segment(profileId)}/inferences/${segment(key)}` }, options);
  }

  /**
   * `POST /v1/profiles/{profile_id}/inferences/{key}/correct`. The subject's value becomes a stated
   * preference or attribute; the inference is deleted.
   */
  correctInference(profileId: string, key: string, body: InferenceCorrection, options: RequestOptions = {}): Promise<Inference> {
    return this.call({ method: "POST", path: `/v1/profiles/${segment(profileId)}/inferences/${segment(key)}/correct`, body }, options);
  }

  /**
   * `POST /v1/profiles/{profile_id}/review-requests`. Sent to the controller's data protection officer with
   * the explanation built from receipts.
   */
  createReviewRequest(profileId: string, body: ReviewRequestCreate, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<ReviewRequest> {
    return this.call({ method: "POST", path: `/v1/profiles/${segment(profileId)}/review-requests`, body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `GET /v1/review-requests`. */
  listReviewRequests(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<ReviewRequestPage> {
    return this.call({ method: "GET", path: "/v1/review-requests", query: { cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /** `POST /v1/review-requests/{request_id}/resolve`. The controller's decision, recorded once. */
  resolveReviewRequest(requestId: string, body: ReviewResolution, options: RequestOptions = {}): Promise<ReviewRequest> {
    return this.call({ method: "POST", path: `/v1/review-requests/${segment(requestId)}/resolve`, body }, options);
  }

  /** `GET /.well-known/niadra-contact-keys.json`. */
  contactKeys(params: { space: string }, options: RequestOptions = {}): Promise<ContactKeys> {
    return this.call({ method: "GET", path: "/.well-known/niadra-contact-keys.json", query: { space: params.space } }, options);
  }

  /** `POST /v1/coordination/check`. */
  check(body: CheckRequest, options: RequestOptions = {}): Promise<CheckResult> {
    return this.call({ method: "POST", path: "/v1/coordination/check", body }, options);
  }

  /** `POST /v1/coordination/check/batch`. */
  checkBatch(body: CheckBatchRequest, options: RequestOptions = {}): Promise<CheckBatchResponse> {
    return this.call({ method: "POST", path: "/v1/coordination/check/batch", body }, options);
  }

  /** `POST /v1/coordination/claims`. */
  claim(body: ClaimRequest, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<OwnershipClaim> {
    return this.call({ method: "POST", path: "/v1/coordination/claims", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/coordination/claims/{claim_id}/release`. */
  releaseClaim(claimId: string, body: ClaimRelease, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<OwnershipClaim> {
    return this.call({ method: "POST", path: `/v1/coordination/claims/${segment(claimId)}/release`, body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/coordination/declare`. */
  declare(body: DeclareRequest, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<DeclareResult> {
    return this.call({ method: "POST", path: "/v1/coordination/declare", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/coordination/effects`. */
  reserveEffect(body: EffectReserve, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Effect | null> {
    return this.call({ method: "POST", path: "/v1/coordination/effects", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/coordination/effects/{effect_id}/settle`. */
  settleEffect(effectId: string, body: EffectSettle, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Effect> {
    return this.call({ method: "POST", path: `/v1/coordination/effects/${segment(effectId)}/settle`, body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /**
   * `GET /v1/coordination/overview`. Ownership that holds now, effects, conflicts, budgets and contacts of
   * the last `days`, in counts.
   */
  overview(params: { days?: number } = {}, options: RequestOptions = {}): Promise<CoordinationOverview> {
    return this.call({ method: "GET", path: "/v1/coordination/overview", query: { days: params.days ?? 7 } }, options);
  }

  /** `GET /v1/coordination/reports`. */
  reports(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<CoordinationReportPage> {
    return this.call({ method: "GET", path: "/v1/coordination/reports", query: { cursor: params.cursor, limit: params.limit ?? 50 } }, options);
  }

  /** `POST /v1/coordination/shadow`. */
  shadow(body: ShadowRequest, options: RequestOptions = {}): Promise<ShadowRun> {
    return this.call({ method: "POST", path: "/v1/coordination/shadow", body }, options);
  }

  /** `POST /v1/handoffs`. */
  createHandoff(body: HandoffCreate, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Handoff> {
    return this.call({ method: "POST", path: "/v1/handoffs", body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `GET /v1/handoffs/{handoff_id}`. */
  readHandoff(handoffId: string, options: RequestOptions = {}): Promise<Handoff> {
    return this.call({ method: "GET", path: `/v1/handoffs/${segment(handoffId)}` }, options);
  }

  /** `POST /v1/handoffs/{handoff_id}/accept`. */
  acceptHandoff(handoffId: string, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Handoff> {
    return this.call({ method: "POST", path: `/v1/handoffs/${segment(handoffId)}/accept`, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `POST /v1/handoffs/{handoff_id}/outcome`. */
  handoffOutcome(handoffId: string, body: HandoffOutcome, params: { idempotency_key?: string } = {}, options: RequestOptions = {}): Promise<Handoff> {
    return this.call({ method: "POST", path: `/v1/handoffs/${segment(handoffId)}/outcome`, body, idempotencyKey: params.idempotency_key ?? uuidv7() }, options);
  }

  /** `GET /v1/suppressions`. */
  suppressions(params: { cursor?: string | null; limit?: number } = {}, options: RequestOptions = {}): Promise<SuppressionPage> {
    return this.call({ method: "GET", path: "/v1/suppressions", query: { cursor: params.cursor, limit: params.limit ?? 200 } }, options);
  }

  /** `GET /v1/suppressions/salt`. */
  suppressionSalt(options: RequestOptions = {}): Promise<SuppressionSalt> {
    return this.call({ method: "GET", path: "/v1/suppressions/salt" }, options);
  }
}
